In [23]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px 


from sklearn.preprocessing import  StandardScaler , MinMaxScaler
from sklearn.metrics import  mean_squared_error , mean_absolute_error
from sklearn.linear_model import  LinearRegression , Ridge
from sklearn.model_selection import  GridSearchCV , cross_val_score , RandomizedSearchCV


from catboost import  CatBoostRegressor
from xgboost import  XGBRegressor

from sklearn.metrics import make_scorer
from sklearn.pipeline import  Pipeline

In [24]:
train = pd.read_csv('/home/nex/Downloads/calorie_expenditure/train.csv')
test = pd.read_csv('/home/nex/Downloads/calorie_expenditure/test.csv')

In [25]:
train.head()

   id     Sex  Age  Height  Weight  Duration  Heart_Rate  Body_Temp  Calories
0   0    male   36   189.0    82.0      26.0       101.0       41.0     150.0
1   1  female   64   163.0    60.0       8.0        85.0       39.7      34.0
2   2  female   51   161.0    64.0       7.0        84.0       39.8      29.0
3   3    male   20   192.0    90.0      25.0       105.0       40.7     140.0
4   4  female   38   166.0    61.0      25.0       102.0       40.6     146.0

In [26]:
train = train.rename(columns={
    "id":"id",
    "Sex": "sex",
    "Age": "age",
    "Height": "height",
    "Weight": "weight",
    "Duration": "duration",
    "Heart_Rate": "heart_rate",
    "Body_Temp": "body_temp",
    "Calories": "calories"
})

In [27]:
train.columns

Index(['id', 'sex', 'age', 'height', 'weight', 'duration', 'heart_rate',
       'body_temp', 'calories'],
      dtype='object')

In [28]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 750000 entries, 0 to 749999
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   id          750000 non-null  int64
 1   sex         750000 non-null  object
 2   age         750000 non-null  int64
 3   height      750000 non-null  float64
 4   weight      750000 non-null  float64
 5   duration    750000 non-null  float64
 6   heart_rate  750000 non-null  float64
 7   body_temp   750000 non-null  float64
 8   calories    750000 non-null  float64
dtypes: float64(6), int64(2), object(1)
memory usage: 51.5+ MB

In [29]:
train.isnull().sum()

id            0
sex           0
age           0
height        0
weight        0
duration      0
heart_rate    0
body_temp     0
calories      0
dtype: int64

In [30]:
train.duplicated().sum()

np.int64(0)

In [31]:
train.describe()

,id,age,height,weight,duration,heart_rate,body_temp,calories
count,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000,750000.000000
mean,374999.500000,41.420404,174.697685,75.145668,15.421015,95.483995,40.036253,88.282781
std,216506.495284,15.175049,12.824496,13.982704,8.354095,9.449845,0.779875,62.395349
min,0.000000,20.000000,126.000000,36.000000,1.000000,67.000000,37.100000,1.000000
25%,187499.750000,28.000000,164.000000,63.000000,8.000000,88.000000,39.600000,34.000000
50%,374999.500000,40.000000,174.000000,74.000000,15.000000,95.000000,40.300000,77.000000
75%,562499.250000,52.000000,185.000000,87.000000,23.000000,103.000000,40.700000,136.000000
max,749999.000000,79.000000,222.000000,132.000000,30.000000,128.000000,41.500000,314.000000

In [32]:
train["bmi"] = train["weight"]/(train["height"]/(100)**2)
train['sex'] = train['sex'].map({'male': 1, 'female': 0})

In [33]:
X_train = train.drop(columns = ["calories","id"],axis=1)
y_train = train["calories"]

In [34]:
xgb_pipe = Pipeline([
    ("scaler1",StandardScaler()),
    ("model1",XGBRegressor())
])


cat_pipe = Pipeline([
    ("scaler2",StandardScaler()),
    ("model2",CatBoostRegressor())
])

In [35]:
def rmsle(y_true, y_pred):
    y_true = np.maximum(0, y_true)
    y_pred = np.maximum(0, y_pred)
    return np.sqrt(np.mean((np.log1p(y_pred) - np.log1p(y_true))**2))

rmsle_scorer = make_scorer(rmsle, greater_is_better=False)

In [36]:
cat_params = {
    'model2__iterations': [100, 200],
    'model2__depth': [4, 6, 8],
    'model2__learning_rate': [0.01, 0.1, 0.2],
    'model2__l2_leaf_reg': [1, 3, 5]
}

xgb_params = {
    'model1__n_estimators': [100, 200],
    'model1__max_depth': [3, 6, 8],
    'model1__learning_rate': [0.01, 0.1, 0.2],
    'model1__reg_lambda': [0.5, 1, 2]
}


cat_search = RandomizedSearchCV(
    cat_pipe,
    cat_params,
    n_iter=10, 
    scoring=rmsle_scorer, 
    cv=5,
    verbose=1, 
    n_jobs=-1,
    random_state=42
)


xgb_search = RandomizedSearchCV(
    xgb_pipe,
    xgb_params,
    n_iter=10,
    scoring = rmsle_scorer,
    cv=5,
    verbose=1, 
    n_jobs=-1,
    random_state=42
)

In [37]:
xgb_search.fit(X_train,y_train)
cat_search.fit(X_train,y_train)



cat_rmsle = -cat_search.best_score_
xgb_rmsle = -xgb_search.best_score_

print("CatBoost RMSLE:", cat_rmsle)
print("XGBoost RMSLE:", xgb_rmsle)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
Fitting 5 folds for each of 10 candidates, totalling 50 fits
0:	learn: 56.6043463	total: 991ms	remaining: 1m 38s
0:	learn: 56.5629235	total: 1.01s	remaining: 1m 39s
0:	learn: 56.5687116	total: 775ms	remaining: 1m 16s
0:	learn: 56.4855722	total: 1.49s	remaining: 4m 55s
1:	learn: 51.3705875	total: 1.54s	remaining: 1m 15s
1:	learn: 51.3748792	total: 1.03s	remaining: 50.5s
1:	learn: 51.4134619	total: 1.8s	remaining: 1m 28s
0:	learn: 56.6055169	total: 1.27s	remaining: 2m 6s
2:	learn: 46.6343476	total: 1.84s	remaining: 59.5s
1:	learn: 51.1594844	total: 1.9s	remaining: 3m 8s
2:	learn: 46.6376396	total: 1.37s	remaining: 44.4s
0:	learn: 56.5912294	total: 852ms	remaining: 1m 24s
2:	learn: 46.6753010	total: 2.22s	remaining: 1m 11s
0:	learn: 56.5204946	total: 1.07s	remaining: 3m 32s
3:	learn: 42.3924188	total: 2.19s	remaining: 52.6s
0:	learn: 56.4845593	total: 1.22s	remaining: 4m 2s
1:	learn: 51.4126960	total: 1.66s	remaining: 1m 21s
2:	learn: 46.3270016	total: 2.32s	remaining: 2m 32s
3:	learn: 42.4270014	total: 2.48s	remaining: 59.5s
1:	learn: 51.1890384	total: 1.35s	remaining: 2m 13s
1:	learn: 51.3813424	total: 1.34s	remaining: 1m 5s
2:	learn: 46.3582767	total: 1.55s	remaining: 1m 42s
1:	learn: 51.1611905	total: 1.73s	remaining: 2m 51s
3:	learn: 42.3875324	total: 2.14s	remaining: 51.5s
4:	learn: 38.5488806	total: 2.75s	remaining: 52.3s
4:	learn: 38.6043154	total: 2.87s	remaining: 54.5s
3:	learn: 42.0309807	total: 2.81s	remaining: 2m 17s
2:	learn: 46.6739436	total: 2.33s	remaining: 1m 15s
3:	learn: 42.0432515	total: 1.83s	remaining: 1m 29s
3:	learn: 42.4247284	total: 2.5s	remaining: 1m
2:	learn: 46.6625446	total: 1.86s	remaining: 1m
4:	learn: 38.1274353	total: 3.21s	remaining: 2m 5s
5:	learn: 35.1417104	total: 3.21s	remaining: 50.3s
2:	learn: 46.3261223	total: 2.25s	remaining: 2m 27s
4:	learn: 38.1456251	total: 2.18s	remaining: 1m 25s
5:	learn: 35.1969240	total: 3.36s	remaining: 52.7s
4:	learn: 38.5686301	total: 2.81s	remaining: 53.4s
3:	learn: 42.4308743	total: 2.21s	remaining: 53.1s
4:	learn: 38.6024021	total: 2.93s	remaining: 55.6s
5:	learn: 35.1564421	total: 3.02s	remaining: 47.4s
4:	learn: 38.5988931	total: 2.48s	remaining: 47.1s
5:	learn: 34.5770911	total: 3.68s	remaining: 1m 59s
5:	learn: 34.6130526	total: 2.68s	remaining: 1m 26s
6:	learn: 32.0113358	total: 3.79s	remaining: 50.3s
6:	learn: 32.1287404	total: 3.77s	remaining: 50s
6:	learn: 32.0901935	total: 3.22s	remaining: 42.8s
3:	learn: 42.0200498	total: 2.96s	remaining: 2m 24s
6:	learn: 31.4572887	total: 2.91s	remaining: 1m 20s
5:	learn: 35.1958873	total: 3.52s	remaining: 55.2s
7:	learn: 29.2455625	total: 4.19s	remaining: 48.1s
7:	learn: 29.2684447	total: 3.61s	remaining: 41.5s
5:	learn: 35.1728810	total: 3s	remaining: 47s
6:	learn: 31.4123879	total: 4.24s	remaining: 1m 56s
6:	learn: 32.1282187	total: 3.77s	remaining: 50.1s
7:	learn: 28.5744164	total: 3.31s	remaining: 1m 19s
7:	learn: 28.5434523	total: 4.44s	remaining: 1m 46s
8:	learn: 26.6865126	total: 4.46s	remaining: 45s
7:	learn: 29.3225263	total: 4.43s	remaining: 51s
4:	learn: 38.1302365	total: 3.58s	remaining: 2m 19s
8:	learn: 26.7298989	total: 3.98s	remaining: 40.2s
8:	learn: 25.9873734	total: 4.7s	remaining: 1m 39s
6:	learn: 32.0573099	total: 3.56s	remaining: 47.3s
7:	learn: 29.3212073	total: 4.2s	remaining: 48.3s
8:	learn: 25.9998298	total: 3.71s	remaining: 1m 18s
8:	learn: 26.7588827	total: 4.84s	remaining: 48.9s
5:	learn: 34.5947435	total: 4.01s	remaining: 2m 9s
9:	learn: 24.4129317	total: 5s	remaining: 45s
9:	learn: 24.4449848	total: 4.48s	remaining: 40.3s
9:	learn: 24.4763905	total: 5.07s	remaining: 45.6s
6:	learn: 31.4324876	total: 4.22s	remaining: 1m 56s
8:	learn: 26.7643813	total: 4.65s	remaining: 47s
7:	learn: 29.2494630	total: 4.05s	remaining: 46.5s
9:	learn: 23.6599096	total: 4.18s	remaining: 1m 19s
9:	learn: 23.6546709	total: 5.29s	remaining: 1m 40s
9:	learn: 24.4889097	total: 4.81s	remaining: 43.3s
10:	learn: 22.3458406	total: 5.46s	remaining: 44.2s
10:	learn: 22.3908668	total: 5s	remaining: 40.5s
10:	learn: 22.4043824	total: 5.62s	remaining: 45.4s
10:	learn: 22.4176043	total: 5.09s	remaining: 41.2s
7:	learn: 28.5570409	total: 4.73s	remaining: 1m 53s
8:	learn: 26.7411576	total: 4.58s	remaining: 46.4s
10:	learn: 21.5504981	total: 5.86s	remaining: 1m 40s
10:	learn: 21.5523288	total: 4.78s	remaining: 1m 22s
11:	learn: 20.5463040	total: 5.28s	remaining: 38.7s
11:	learn: 20.5072783	total: 5.9s	remaining: 43.3s
11:	learn: 20.5718956	total: 5.52s	remaining: 40.5s
9:	learn: 24.4416840	total: 4.97s	remaining: 44.8s
11:	learn: 20.5623021	total: 6.16s	remaining: 45.2s
11:	learn: 19.6714573	total: 5.11s	remaining: 1m 20s
8:	learn: 26.0024826	total: 5.28s	remaining: 1m 52s
12:	learn: 18.8619634	total: 5.68s	remaining: 38s
12:	learn: 18.8366381	total: 6.36s	remaining: 42.6s
12:	learn: 17.9615675	total: 5.29s	remaining: 1m 16s
11:	learn: 19.6722964	total: 6.43s	remaining: 1m 40s
13:	learn: 16.4406911	total: 5.48s	remaining: 1m 12s
10:	learn: 22.3938059	total: 5.4s	remaining: 43.7s
12:	learn: 18.9140577	total: 6.05s	remaining: 40.5s
13:	learn: 17.3492747	total: 6.09s	remaining: 37.4s
13:	learn: 17.3279238	total: 6.7s	remaining: 41.2s
12:	learn: 18.8867296	total: 6.73s	remaining: 45.1s
9:	learn: 23.6601786	total: 5.84s	remaining: 1m 51s
14:	learn: 15.0595607	total: 5.82s	remaining: 1m 11s
12:	learn: 17.9801821	total: 6.96s	remaining: 1m 40s
11:	learn: 20.5247211	total: 5.76s	remaining: 42.2s
13:	learn: 17.4244313	total: 6.4s	remaining: 39.3s
14:	learn: 15.9709641	total: 7.04s	remaining: 39.9s
14:	learn: 16.0040898	total: 6.54s	remaining: 37.1s
13:	learn: 17.3841630	total: 7.13s	remaining: 43.8s
14:	learn: 16.0598932	total: 6.57s	remaining: 37.2s
12:	learn: 18.8601627	total: 6.07s	remaining: 40.6s
10:	learn: 21.5549098	total: 6.3s	remaining: 1m 48s
15:	learn: 14.7567521	total: 7.34s	remaining: 38.6s
15:	learn: 14.7823867	total: 6.78s	remaining: 35.6s
15:	learn: 14.8425653	total: 6.88s	remaining: 36.1s
13:	learn: 17.3639049	total: 6.31s	remaining: 38.8s
15:	learn: 13.8359378	total: 6.49s	remaining: 1m 14s
13:	learn: 16.4489865	total: 7.66s	remaining: 1m 41s
11:	learn: 19.6738127	total: 6.72s	remaining: 1m 45s
14:	learn: 16.0235831	total: 7.69s	remaining: 43.6s
16:	learn: 13.7489745	total: 7.13s	remaining: 34.8s
16:	learn: 13.6515349	total: 7.78s	remaining: 38s
16:	learn: 13.6710549	total: 7.19s	remaining: 35.1s
16:	learn: 12.7319078	total: 6.87s	remaining: 1m 13s
12:	learn: 17.9921124	total: 7.05s	remaining: 1m 41s
14:	learn: 15.0764708	total: 8.04s	remaining: 1m 39s
17:	learn: 12.7373358	total: 7.49s	remaining: 34.1s
14:	learn: 16.0079188	total: 6.91s	remaining: 39.2s
17:	learn: 11.7313267	total: 7.1s	remaining: 1m 11s
15:	learn: 14.8070600	total: 8.18s	remaining: 42.9s
17:	learn: 12.6808791	total: 7.61s	remaining: 34.7s
17:	learn: 12.6731404	total: 8.28s	remaining: 37.7s
18:	learn: 11.7987999	total: 8.46s	remaining: 36.1s
18:	learn: 11.8583664	total: 7.91s	remaining: 33.7s
15:	learn: 14.7880744	total: 7.33s	remaining: 38.5s
15:	learn: 13.8365800	total: 8.54s	remaining: 1m 38s
18:	learn: 10.8351648	total: 7.48s	remaining: 1m 11s
16:	learn: 13.6976802	total: 8.54s	remaining: 41.7s
18:	learn: 11.7870545	total: 8.02s	remaining: 34.2s
13:	learn: 16.4819277	total: 7.77s	remaining: 1m 43s
17:	learn: 12.7067346	total: 8.73s	remaining: 39.8s
19:	learn: 10.9986499	total: 8.85s	remaining: 35.4s
16:	learn: 12.7324500	total: 8.89s	remaining: 1m 35s
18:	learn: 11.8225529	total: 8.89s	remaining: 37.9s
19:	learn: 10.0411529	total: 7.85s	remaining: 1m 10s
19:	learn: 11.0252184	total: 9.02s	remaining: 36.1s
19:	learn: 11.0652563	total: 8.52s	remaining: 34.1s
14:	learn: 15.1097221	total: 8.2s	remaining: 1m 41s
19:	learn: 10.9753134	total: 8.59s	remaining: 34.4s
16:	learn: 13.6818731	total: 8.03s	remaining: 39.2s
20:	learn: 10.2818646	total: 9.28s	remaining: 34.9s
20:	learn: 10.2487687	total: 8.76s	remaining: 33s
17:	learn: 11.7362102	total: 9.39s	remaining: 1m 35s
20:	learn: 9.3351293	total: 8.4s	remaining: 1m 11s
20:	learn: 10.3032608	total: 9.51s	remaining: 35.8s
20:	learn: 10.3519928	total: 8.96s	remaining: 33.7s
17:	learn: 12.6775634	total: 8.38s	remaining: 38.2s
21:	learn: 9.6067289	total: 8.98s	remaining: 31.9s
15:	learn: 13.8719902	total: 8.63s	remaining: 1m 39s
18:	learn: 10.8490874	total: 9.69s	remaining: 1m 32s
18:	learn: 11.7850656	total: 8.59s	remaining: 36.6s
21:	learn: 9.6421438	total: 9.89s	remaining: 35.1s
21:	learn: 9.7206792	total: 9.32s	remaining: 33s
19:	learn: 10.9833767	total: 8.8s	remaining: 35.2s
21:	learn: 8.6834615	total: 9s	remaining: 1m 12s
20:	learn: 10.2428767	total: 8.9s	remaining: 33.5s
21:	learn: 9.6592833	total: 10.1s	remaining: 35.8s
16:	learn: 12.7664977	total: 9.15s	remaining: 1m 38s
21:	learn: 9.5982041	total: 9.01s	remaining: 31.9s
22:	learn: 9.0230890	total: 9.66s	remaining: 32.3s
19:	learn: 10.0613363	total: 10.3s	remaining: 1m 32s
22:	learn: 9.1252278	total: 9.69s	remaining: 32.4s
22:	learn: 9.0842804	total: 10.3s	remaining: 34.5s
22:	learn: 9.0642932	total: 10.4s	remaining: 34.8s
17:	learn: 11.7705862	total: 9.5s	remaining: 1m 36s
22:	learn: 9.0107614	total: 9.25s	remaining: 31s
22:	learn: 8.1119180	total: 9.45s	remaining: 1m 12s
23:	learn: 8.5149851	total: 9.98s	remaining: 31.6s
23:	learn: 8.5590778	total: 10.7s	remaining: 33.9s
20:	learn: 9.3399090	total: 10.8s	remaining: 1m 31s
23:	learn: 8.5567840	total: 10.8s	remaining: 34.1s
24:	learn: 8.1010123	total: 10.8s	remaining: 32.5s
23:	learn: 8.5018381	total: 9.68s	remaining: 30.6s
23:	learn: 8.5979089	total: 10.3s	remaining: 32.8s
18:	learn: 10.8705292	total: 9.99s	remaining: 1m 35s
21:	learn: 8.7131268	total: 11.1s	remaining: 1m 29s
23:	learn: 7.6039153	total: 9.98s	remaining: 1m 13s
24:	learn: 8.0487626	total: 10.5s	remaining: 31.4s
25:	learn: 7.7016900	total: 11.1s	remaining: 31.7s
24:	learn: 8.0935154	total: 11.4s	remaining: 34.1s
22:	learn: 8.1538097	total: 11.4s	remaining: 1m 27s
24:	learn: 8.0266742	total: 10.1s	remaining: 30.4s
25:	learn: 7.6239128	total: 10.8s	remaining: 30.7s
24:	learn: 8.1351366	total: 10.8s	remaining: 32.5s
24:	learn: 7.1583182	total: 10.4s	remaining: 1m 12s
19:	learn: 10.0721579	total: 10.5s	remaining: 1m 34s
26:	learn: 7.3209184	total: 11.6s	remaining: 31.4s
20:	learn: 9.3634608	total: 10.7s	remaining: 1m 31s
26:	learn: 7.2561678	total: 11.2s	remaining: 30.2s
25:	learn: 7.7044078	total: 11.2s	remaining: 31.8s
25:	learn: 6.7654442	total: 10.7s	remaining: 1m 11s
25:	learn: 7.6222314	total: 10.6s	remaining: 30.2s
25:	learn: 7.6660641	total: 11.9s	remaining: 33.8s
23:	learn: 7.6564014	total: 11.9s	remaining: 1m 27s
27:	learn: 6.9950843	total: 11.9s	remaining: 30.6s
26:	learn: 7.3189295	total: 11.4s	remaining: 30.9s
26:	learn: 7.2440658	total: 10.9s	remaining: 29.5s
26:	learn: 6.4117422	total: 11.1s	remaining: 1m 11s
21:	learn: 8.7245860	total: 11.2s	remaining: 1m 30s
28:	learn: 6.6888199	total: 12.2s	remaining: 29.8s
26:	learn: 7.2877743	total: 12.2s	remaining: 33s
27:	learn: 6.9304362	total: 11.6s	remaining: 29.9s
24:	learn: 7.2091902	total: 12.3s	remaining: 1m 26s
27:	learn: 6.9843833	total: 11.8s	remaining: 30.4s
27:	learn: 6.9261200	total: 11.2s	remaining: 28.8s
29:	learn: 6.4279870	total: 12.5s	remaining: 29.3s
28:	learn: 6.6926579	total: 12s	remaining: 29.3s
27:	learn: 6.9676714	total: 12.6s	remaining: 32.4s
27:	learn: 6.0945371	total: 11.6s	remaining: 1m 11s
28:	learn: 6.6278162	total: 12.1s	remaining: 29.6s
29:	learn: 6.4319597	total: 12.2s	remaining: 28.5s
30:	learn: 6.1983260	total: 12.8s	remaining: 28.5s
25:	learn: 6.8161405	total: 12.9s	remaining: 1m 26s
22:	learn: 8.1544208	total: 11.9s	remaining: 1m 31s
30:	learn: 6.2027905	total: 12.4s	remaining: 27.6s
28:	learn: 6.6741133	total: 13s	remaining: 31.8s
29:	learn: 6.3657955	total: 12.5s	remaining: 29.2s
28:	learn: 6.6312208	total: 11.9s	remaining: 29.1s
31:	learn: 5.9940463	total: 13.2s	remaining: 28s
28:	learn: 5.8261786	total: 12.2s	remaining: 1m 11s
29:	learn: 6.4135961	total: 13.2s	remaining: 30.9s
31:	learn: 5.9782130	total: 12.6s	remaining: 26.9s
23:	learn: 7.6596931	total: 12.3s	remaining: 1m 30s
26:	learn: 6.4752372	total: 13.4s	remaining: 1m 25s
30:	learn: 6.1315193	total: 12.8s	remaining: 28.6s
29:	learn: 6.3787856	total: 12.2s	remaining: 28.4s
32:	learn: 5.8183320	total: 13.5s	remaining: 27.4s
24:	learn: 7.2127953	total: 12.6s	remaining: 1m 28s
29:	learn: 5.5897825	total: 12.6s	remaining: 1m 11s
30:	learn: 6.1656568	total: 13.6s	remaining: 30.4s
31:	learn: 5.9297819	total: 13.2s	remaining: 28s
32:	learn: 5.7977515	total: 13.2s	remaining: 26.8s
33:	learn: 5.6326473	total: 13.8s	remaining: 26.8s
27:	learn: 6.1583731	total: 13.8s	remaining: 1m 25s
30:	learn: 6.1332145	total: 12.7s	remaining: 28.2s
32:	learn: 5.7306531	total: 13.4s	remaining: 27.2s
25:	learn: 6.8174901	total: 13s	remaining: 1m 27s
31:	learn: 5.9650728	total: 14.1s	remaining: 30s
33:	learn: 5.5582070	total: 13.6s	remaining: 26.3s
33:	learn: 5.6284981	total: 13.6s	remaining: 26.3s
34:	learn: 5.4884032	total: 14.3s	remaining: 26.5s
28:	learn: 5.8883721	total: 14.3s	remaining: 1m 24s
31:	learn: 5.9320700	total: 13.1s	remaining: 27.8s
34:	learn: 5.4875954	total: 13.8s	remaining: 25.6s
26:	learn: 6.4621040	total: 13.5s	remaining: 1m 26s
30:	learn: 5.3748988	total: 13.5s	remaining: 1m 13s
34:	learn: 5.4146728	total: 14s	remaining: 25.9s
29:	learn: 5.6380123	total: 14.7s	remaining: 1m 23s
32:	learn: 5.7725251	total: 14.7s	remaining: 29.8s
32:	learn: 5.7518002	total: 13.5s	remaining: 27.4s
35:	learn: 5.3516169	total: 14.2s	remaining: 25.3s
30:	learn: 5.4250327	total: 14.8s	remaining: 1m 20s
35:	learn: 5.3462098	total: 14.8s	remaining: 26.3s
27:	learn: 6.1513196	total: 13.9s	remaining: 1m 25s
33:	learn: 5.5978933	total: 15s	remaining: 29.1s
35:	learn: 5.2819980	total: 14.4s	remaining: 25.6s
36:	learn: 5.2292706	total: 15s	remaining: 25.6s
31:	learn: 5.1885644	total: 14s	remaining: 1m 13s
33:	learn: 5.5933779	total: 13.9s	remaining: 27s
37:	learn: 5.1296968	total: 15.2s	remaining: 24.7s
36:	learn: 5.2338096	total: 14.6s	remaining: 24.9s
36:	learn: 5.1706474	total: 14.7s	remaining: 25.1s
38:	learn: 5.0386846	total: 15.4s	remaining: 24s
28:	learn: 5.8796254	total: 14.4s	remaining: 1m 24s
34:	learn: 5.4446668	total: 15.4s	remaining: 28.6s
31:	learn: 5.2375066	total: 15.5s	remaining: 1m 21s
32:	learn: 5.0258232	total: 14.5s	remaining: 1m 13s
37:	learn: 5.1218390	total: 15s	remaining: 24.5s
39:	learn: 4.9597649	total: 15.6s	remaining: 23.4s
37:	learn: 5.0592018	total: 15.1s	remaining: 24.6s
33:	learn: 4.8821189	total: 14.7s	remaining: 1m 11s
34:	learn: 5.4304651	total: 14.5s	remaining: 27s
35:	learn: 5.3173052	total: 15.9s	remaining: 28.2s
40:	learn: 4.8743645	total: 15.9s	remaining: 22.9s
29:	learn: 5.6418141	total: 15s	remaining: 1m 24s
32:	learn: 5.0770319	total: 16s	remaining: 1m 20s
34:	learn: 4.7537318	total: 15s	remaining: 1m 10s
35:	learn: 5.2989833	total: 14.9s	remaining: 26.4s
38:	learn: 5.0329100	total: 15.5s	remaining: 24.2s
36:	learn: 5.1957597	total: 16.2s	remaining: 27.5s
41:	learn: 4.7971088	total: 16.2s	remaining: 22.3s
38:	learn: 4.9517430	total: 15.6s	remaining: 24.4s
39:	learn: 4.8694079	total: 15.8s	remaining: 23.7s
42:	learn: 4.7415041	total: 16.4s	remaining: 21.7s
39:	learn: 4.9524318	total: 15.8s	remaining: 23.7s
33:	learn: 4.9342859	total: 16.5s	remaining: 1m 20s
43:	learn: 4.6816251	total: 16.5s	remaining: 21s
35:	learn: 4.6413011	total: 15.5s	remaining: 1m 10s
37:	learn: 5.0888437	total: 16.6s	remaining: 27.1s
40:	learn: 4.7886131	total: 16.1s	remaining: 23.1s
36:	learn: 5.1843707	total: 15.4s	remaining: 26.3s
30:	learn: 5.4219627	total: 15.7s	remaining: 1m 25s
44:	learn: 4.6224577	total: 16.7s	remaining: 20.5s
40:	learn: 4.8670698	total: 16.3s	remaining: 23.5s
34:	learn: 4.8038949	total: 17s	remaining: 1m 20s
37:	learn: 5.0765132	total: 15.8s	remaining: 25.7s
31:	learn: 5.2302151	total: 16s	remaining: 1m 24s
41:	learn: 4.7260121	total: 16.4s	remaining: 22.7s
45:	learn: 4.5795319	total: 17s	remaining: 20s
36:	learn: 4.5422060	total: 16.1s	remaining: 1m 10s
41:	learn: 4.8040528	total: 16.6s	remaining: 22.9s
32:	learn: 5.0710741	total: 16.3s	remaining: 1m 22s
46:	learn: 4.5407018	total: 17.3s	remaining: 19.5s
38:	learn: 4.9909896	total: 17.4s	remaining: 27.2s
42:	learn: 4.6602097	total: 16.8s	remaining: 22.3s
38:	learn: 4.9868780	total: 16.2s	remaining: 25.3s
42:	learn: 4.7431357	total: 17s	remaining: 22.5s
39:	learn: 4.9041619	total: 16.4s	remaining: 24.6s
35:	learn: 4.6906527	total: 17.7s	remaining: 1m 20s
33:	learn: 4.9276593	total: 16.7s	remaining: 1m 21s
39:	learn: 4.9114436	total: 17.7s	remaining: 26.6s
47:	learn: 4.5015262	total: 17.7s	remaining: 19.2s
43:	learn: 4.6080055	total: 17.1s	remaining: 21.8s
37:	learn: 4.4595377	total: 16.7s	remaining: 1m 11s
44:	learn: 4.5503008	total: 17.4s	remaining: 21.2s
43:	learn: 4.6747238	total: 17.4s	remaining: 22.1s
38:	learn: 4.3848091	total: 17s	remaining: 1m 10s
40:	learn: 4.8133359	total: 16.8s	remaining: 24.2s
40:	learn: 4.8385771	total: 18.1s	remaining: 26.1s
48:	learn: 4.4636734	total: 18.1s	remaining: 18.9s
34:	learn: 4.7942261	total: 17.3s	remaining: 1m 21s
45:	learn: 4.5044842	total: 17.7s	remaining: 20.7s
36:	learn: 4.5848201	total: 18.3s	remaining: 1m 20s
41:	learn: 4.7725434	total: 18.4s	remaining: 25.4s
44:	learn: 4.6252811	total: 17.7s	remaining: 21.7s
49:	learn: 4.4363262	total: 18.4s	remaining: 18.4s
41:	learn: 4.7477278	total: 17.3s	remaining: 23.8s
42:	learn: 4.7129522	total: 18.6s	remaining: 24.7s
37:	learn: 4.4984389	total: 18.6s	remaining: 1m 19s
46:	learn: 4.4673856	total: 18s	remaining: 20.3s
50:	learn: 4.4076752	total: 18.6s	remaining: 17.9s
39:	learn: 4.3227302	total: 17.6s	remaining: 1m 10s
42:	learn: 4.6906744	total: 17.5s	remaining: 23.1s
35:	learn: 4.6850593	total: 17.7s	remaining: 1m 20s
45:	learn: 4.5775340	total: 18.2s	remaining: 21.3s
51:	learn: 4.3762415	total: 18.8s	remaining: 17.4s
43:	learn: 4.6512274	total: 18.9s	remaining: 24.1s
43:	learn: 4.6264635	total: 17.7s	remaining: 22.6s
52:	learn: 4.3434123	total: 19.1s	remaining: 16.9s
47:	learn: 4.4264332	total: 18.5s	remaining: 20.1s
36:	learn: 4.5818438	total: 18.2s	remaining: 1m 19s
46:	learn: 4.5401561	total: 18.6s	remaining: 21s
44:	learn: 4.5722317	total: 18s	remaining: 22s
38:	learn: 4.4167681	total: 19.3s	remaining: 1m 19s
40:	learn: 4.2581845	total: 18.3s	remaining: 1m 10s
53:	learn: 4.3225562	total: 19.3s	remaining: 16.5s
37:	learn: 4.4964525	total: 18.4s	remaining: 1m 18s
45:	learn: 4.5290638	total: 18.2s	remaining: 21.4s
44:	learn: 4.5927600	total: 19.4s	remaining: 23.8s
54:	learn: 4.2966353	total: 19.5s	remaining: 16s
47:	learn: 4.5009344	total: 18.9s	remaining: 20.5s
48:	learn: 4.3951359	total: 19s	remaining: 19.8s
55:	learn: 4.2790467	total: 19.7s	remaining: 15.5s
46:	learn: 4.4899071	total: 18.5s	remaining: 20.9s
45:	learn: 4.5482014	total: 19.8s	remaining: 23.2s
49:	learn: 4.3539093	total: 19.3s	remaining: 19.3s
39:	learn: 4.3512468	total: 19.9s	remaining: 1m 19s
48:	learn: 4.4685802	total: 19.3s	remaining: 20.1s
46:	learn: 4.5108263	total: 19.9s	remaining: 22.5s
41:	learn: 4.2072109	total: 18.9s	remaining: 1m 11s
38:	learn: 4.4185049	total: 19.1s	remaining: 1m 18s
47:	learn: 4.4472550	total: 18.8s	remaining: 20.4s
40:	learn: 4.2922270	total: 20.2s	remaining: 1m 18s
47:	learn: 4.4687682	total: 20.2s	remaining: 21.9s
56:	learn: 4.2609742	total: 20.2s	remaining: 15.2s
39:	learn: 4.3542278	total: 19.3s	remaining: 1m 17s
48:	learn: 4.4140448	total: 19.1s	remaining: 19.9s
49:	learn: 4.4266724	total: 19.8s	remaining: 19.8s
48:	learn: 4.4361846	total: 20.4s	remaining: 21.2s
42:	learn: 4.1636142	total: 19.3s	remaining: 1m 10s
50:	learn: 4.3203545	total: 19.9s	remaining: 19.1s
49:	learn: 4.4015544	total: 20.5s	remaining: 20.5s
49:	learn: 4.3840015	total: 19.5s	remaining: 19.5s
41:	learn: 4.2344550	total: 20.7s	remaining: 1m 18s
50:	learn: 4.3655704	total: 20.7s	remaining: 19.9s
40:	learn: 4.2943704	total: 19.8s	remaining: 1m 16s
57:	learn: 4.2388087	total: 20.7s	remaining: 15s
43:	learn: 4.1200589	total: 19.8s	remaining: 1m 10s

Exception ignored in: <function ResourceTracker.__del__ at 0x7f5ea958ea20>
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

198:	learn: 3.4755967	total: 1m 29s	remaining: 449ms
98:	learn: 24.8928047	total: 48.7s	remaining: 49.7s
102:	learn: 24.0241718	total: 51.1s	remaining: 48.1s
121:	learn: 3.5823425	total: 51.7s	remaining: 33.1s
96:	learn: 25.3694111	total: 48.4s	remaining: 51.4s
122:	learn: 3.5805034	total: 52.1s	remaining: 32.6s
115:	learn: 3.5863251	total: 52.3s	remaining: 37.8s
103:	learn: 23.8106879	total: 51.4s	remaining: 47.5s
199:	learn: 3.4749021	total: 1m 29s	remaining: 0us
99:	learn: 24.6698200	total: 49.3s	remaining: 49.3s
104:	learn: 23.5993926	total: 51.7s	remaining: 46.8s
97:	learn: 25.1431742	total: 49s	remaining: 51s
116:	learn: 3.5848924	total: 52.7s	remaining: 37.4s
123:	learn: 3.5786444	total: 52.5s	remaining: 32.2s

/usr/lib/python3.13/site-packages/joblib/externals/loky/process_executor.py:752: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

100:	learn: 24.4509420	total: 49.7s	remaining: 48.7s
105:	learn: 23.3900557	total: 52s	remaining: 46.1s

Exception ignored in: <function ResourceTracker.__del__ at 0x7fd0a6f9aa20>
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

0:	learn: 61.8268651	total: 396ms	remaining: 1m 18s
124:	learn: 3.5769834	total: 52.9s	remaining: 31.7s
98:	learn: 24.9184237	total: 49.5s	remaining: 50.5s
117:	learn: 3.5832431	total: 53.3s	remaining: 37s
106:	learn: 23.1831234	total: 52.5s	remaining: 45.6s
99:	learn: 24.6966605	total: 49.7s	remaining: 49.7s
101:	learn: 24.2346604	total: 50.3s	remaining: 48.3s
125:	learn: 3.5749528	total: 53.3s	remaining: 31.3s
100:	learn: 24.4785132	total: 50.1s	remaining: 49.1s
118:	learn: 3.5819347	total: 53.7s	remaining: 36.5s
107:	learn: 22.9770684	total: 52.9s	remaining: 45.1s
1:	learn: 61.2412735	total: 1.12s	remaining: 1m 51s
102:	learn: 24.0176845	total: 50.7s	remaining: 47.7s
126:	learn: 3.5729802	total: 53.7s	remaining: 30.8s
101:	learn: 24.2626123	total: 50.4s	remaining: 48.4s
119:	learn: 3.5795958	total: 54.2s	remaining: 36.1s
127:	learn: 3.5707841	total: 54s	remaining: 30.4s
103:	learn: 23.8044411	total: 51.1s	remaining: 47.2s
2:	learn: 60.6592884	total: 1.71s	remaining: 1m 52s
108:	learn: 22.7742234	total: 53.5s	remaining: 44.7s
102:	learn: 24.0453816	total: 50.8s	remaining: 47.8s
128:	learn: 3.5700462	total: 54.4s	remaining: 29.9s
120:	learn: 3.5777651	total: 54.6s	remaining: 35.6s
104:	learn: 23.5930293	total: 51.5s	remaining: 46.6s
3:	learn: 60.0827618	total: 2.1s	remaining: 1m 42s
103:	learn: 23.8319045	total: 51.2s	remaining: 47.3s
105:	learn: 23.3837166	total: 51.8s	remaining: 45.9s
109:	learn: 22.5761502	total: 54.1s	remaining: 44.3s
121:	learn: 3.5759202	total: 55s	remaining: 35.2s
129:	learn: 3.5683456	total: 54.9s	remaining: 29.6s
104:	learn: 23.6204633	total: 51.6s	remaining: 46.7s
110:	learn: 22.3792954	total: 54.4s	remaining: 43.7s
106:	learn: 23.1768265	total: 52.2s	remaining: 45.3s
4:	learn: 59.5150776	total: 2.65s	remaining: 1m 43s
111:	learn: 22.1827491	total: 54.7s	remaining: 43s
122:	learn: 3.5745997	total: 55.6s	remaining: 34.8s
107:	learn: 22.9707204	total: 52.5s	remaining: 44.7s
130:	learn: 3.5656927	total: 55.5s	remaining: 29.2s
105:	learn: 23.4091477	total: 52.1s	remaining: 46.2s
5:	learn: 58.9541312	total: 3.25s	remaining: 1m 44s
112:	learn: 21.9860766	total: 55.1s	remaining: 42.4s
108:	learn: 22.7677933	total: 52.9s	remaining: 44.1s
123:	learn: 3.5726308	total: 56.2s	remaining: 34.4s
106:	learn: 23.2024682	total: 52.6s	remaining: 45.7s
131:	learn: 3.5643630	total: 56.1s	remaining: 28.9s
6:	learn: 58.3956556	total: 3.6s	remaining: 1m 39s
109:	learn: 22.5691406	total: 53.2s	remaining: 43.5s
113:	learn: 21.7947542	total: 55.5s	remaining: 41.9s
124:	learn: 3.5707924	total: 56.6s	remaining: 34s
107:	learn: 22.9959893	total: 53s	remaining: 45.2s
132:	learn: 3.5629475	total: 56.5s	remaining: 28.4s
7:	learn: 57.8450249	total: 4.1s	remaining: 1m 38s
114:	learn: 21.6029795	total: 56s	remaining: 41.4s
110:	learn: 22.3720856	total: 53.8s	remaining: 43.1s
125:	learn: 3.5686630	total: 57s	remaining: 33.5s
108:	learn: 22.7932818	total: 53.5s	remaining: 44.7s
133:	learn: 3.5619231	total: 56.9s	remaining: 28s
111:	learn: 22.1739301	total: 54.1s	remaining: 42.5s
8:	learn: 57.2978501	total: 4.6s	remaining: 1m 37s
115:	learn: 21.4139155	total: 56.5s	remaining: 40.9s
126:	learn: 3.5668774	total: 57.5s	remaining: 33s
112:	learn: 21.9772103	total: 54.4s	remaining: 41.9s
134:	learn: 3.5599385	total: 57.4s	remaining: 27.6s
9:	learn: 56.7557954	total: 4.96s	remaining: 1m 34s
109:	learn: 22.5929636	total: 54.1s	remaining: 44.3s
116:	learn: 21.2261887	total: 57s	remaining: 40.4s
113:	learn: 21.7858010	total: 54.7s	remaining: 41.3s
135:	learn: 3.5587049	total: 57.7s	remaining: 27.2s
0:	learn: 61.8127268	total: 624ms	remaining: 2m 4s
127:	learn: 3.5655505	total: 58s	remaining: 32.6s
10:	learn: 56.2197920	total: 5.47s	remaining: 1m 33s
110:	learn: 22.3959336	total: 54.6s	remaining: 43.8s
117:	learn: 21.0394418	total: 57.5s	remaining: 40s
128:	learn: 3.5638671	total: 58.4s	remaining: 32.1s
136:	learn: 3.5569544	total: 58.2s	remaining: 26.8s
114:	learn: 21.5940550	total: 55.5s	remaining: 41s
129:	learn: 3.5615957	total: 58.6s	remaining: 31.6s
11:	learn: 55.6886646	total: 5.99s	remaining: 1m 33s
111:	learn: 22.1975565	total: 55.1s	remaining: 43.3s
118:	learn: 20.8566894	total: 58s	remaining: 39.5s
137:	learn: 3.5554504	total: 58.7s	remaining: 26.4s
1:	learn: 61.2273341	total: 1.47s	remaining: 2m 25s
130:	learn: 3.5602429	total: 58.9s	remaining: 31s
115:	learn: 21.4050030	total: 55.8s	remaining: 40.4s
12:	learn: 55.1678982	total: 6.46s	remaining: 1m 32s
116:	learn: 21.2170464	total: 56.1s	remaining: 39.8s
112:	learn: 22.0010096	total: 55.7s	remaining: 42.9s
2:	learn: 60.6454350	total: 1.91s	remaining: 2m 5s
119:	learn: 20.6753728	total: 58.5s	remaining: 39s
0:	learn: 61.8015767	total: 415ms	remaining: 1m 22s
138:	learn: 3.5539345	total: 59.2s	remaining: 26s
131:	learn: 3.5588839	total: 59.4s	remaining: 30.6s
13:	learn: 54.6474423	total: 6.98s	remaining: 1m 32s
1:	learn: 61.2434097	total: 769ms	remaining: 1m 16s
132:	learn: 3.5570143	total: 59.7s	remaining: 30.1s
117:	learn: 21.0304026	total: 56.6s	remaining: 39.3s
120:	learn: 20.4971283	total: 59.1s	remaining: 38.6s
139:	learn: 3.5521340	total: 59.7s	remaining: 25.6s
2:	learn: 60.6905034	total: 1.06s	remaining: 1m 9s
113:	learn: 21.8097136	total: 56.4s	remaining: 42.6s
3:	learn: 60.0689812	total: 2.65s	remaining: 2m 10s
14:	learn: 54.1315362	total: 7.43s	remaining: 1m 31s
133:	learn: 3.5555487	total: 1m	remaining: 29.6s
3:	learn: 60.1420553	total: 1.35s	remaining: 1m 6s
114:	learn: 21.6172557	total: 56.7s	remaining: 41.9s
4:	learn: 59.5006110	total: 2.9s	remaining: 1m 53s
121:	learn: 20.3182362	total: 59.5s	remaining: 38.1s
140:	learn: 3.5507821	total: 1m	remaining: 25.2s
118:	learn: 20.8469368	total: 57.3s	remaining: 39s
4:	learn: 59.5992516	total: 1.63s	remaining: 1m 3s
115:	learn: 21.4268331	total: 57s	remaining: 41.3s
5:	learn: 59.0608016	total: 1.75s	remaining: 56.6s
119:	learn: 20.6649028	total: 57.6s	remaining: 38.4s
134:	learn: 3.5541481	total: 1m	remaining: 29.2s
5:	learn: 58.9397453	total: 3.45s	remaining: 1m 51s
141:	learn: 3.5493672	total: 1m	remaining: 24.8s
120:	learn: 20.4864905	total: 57.7s	remaining: 37.7s
122:	learn: 20.1429952	total: 1m	remaining: 37.6s
15:	learn: 53.6223103	total: 8.2s	remaining: 1m 34s
116:	learn: 21.2389196	total: 57.5s	remaining: 40.8s
6:	learn: 58.5285085	total: 2.26s	remaining: 1m 2s
142:	learn: 3.5480017	total: 1m 1s	remaining: 24.4s
16:	learn: 53.1177651	total: 8.62s	remaining: 1m 32s
135:	learn: 3.5526989	total: 1m 1s	remaining: 28.9s
6:	learn: 58.3799479	total: 3.94s	remaining: 1m 48s
121:	learn: 20.3076290	total: 58.2s	remaining: 37.2s
117:	learn: 21.0520913	total: 57.8s	remaining: 40.2s
7:	learn: 58.0042292	total: 2.63s	remaining: 1m 3s
123:	learn: 19.9691640	total: 1m	remaining: 37.2s
143:	learn: 3.5464900	total: 1m 1s	remaining: 23.9s
136:	learn: 3.5512199	total: 1m 1s	remaining: 28.3s
118:	learn: 20.8680057	total: 58.1s	remaining: 39.6s
122:	learn: 20.1324255	total: 58.7s	remaining: 36.8s
8:	learn: 57.4849863	total: 2.99s	remaining: 1m 3s
7:	learn: 57.8293930	total: 4.51s	remaining: 1m 48s
17:	learn: 52.6192318	total: 9.23s	remaining: 1m 33s
144:	learn: 3.5454424	total: 1m 1s	remaining: 23.5s
9:	learn: 56.9726055	total: 3.16s	remaining: 1m
137:	learn: 3.5496879	total: 1m 2s	remaining: 27.9s
124:	learn: 19.7977948	total: 1m 1s	remaining: 36.8s
119:	learn: 20.6859964	total: 58.6s	remaining: 39.1s
8:	learn: 57.2826822	total: 4.79s	remaining: 1m 41s
123:	learn: 19.9576674	total: 59.1s	remaining: 36.2s
18:	learn: 52.1261338	total: 9.65s	remaining: 1m 31s
145:	learn: 3.5438170	total: 1m 2s	remaining: 23s
10:	learn: 56.4642839	total: 3.49s	remaining: 60s
138:	learn: 3.5483135	total: 1m 2s	remaining: 27.4s
124:	learn: 19.7847567	total: 59.5s	remaining: 35.7s
11:	learn: 55.9588095	total: 3.78s	remaining: 59.2s
125:	learn: 19.6267085	total: 1m 1s	remaining: 36.4s
120:	learn: 20.5079035	total: 59.1s	remaining: 38.6s
19:	learn: 51.6353802	total: 10.1s	remaining: 1m 31s
146:	learn: 3.5422161	total: 1m 2s	remaining: 22.6s
139:	learn: 3.5469429	total: 1m 2s	remaining: 27s
125:	learn: 19.6140968	total: 59.8s	remaining: 35.1s
12:	learn: 55.4630151	total: 4.04s	remaining: 58.1s
9:	learn: 56.7407844	total: 5.56s	remaining: 1m 45s
13:	learn: 54.9709482	total: 4.23s	remaining: 56.2s
20:	learn: 51.1502412	total: 10.5s	remaining: 1m 29s
126:	learn: 19.4454350	total: 1m	remaining: 34.5s
126:	learn: 19.4569649	total: 1m 2s	remaining: 35.9s
14:	learn: 54.4835972	total: 4.42s	remaining: 54.6s
140:	learn: 3.5457766	total: 1m 3s	remaining: 26.6s
127:	learn: 19.2758817	total: 1m	remaining: 33.9s
147:	learn: 3.5406944	total: 1m 3s	remaining: 22.2s
10:	learn: 56.2048580	total: 6.17s	remaining: 1m 46s
15:	learn: 54.0017261	total: 4.7s	remaining: 54s
21:	learn: 50.6709108	total: 10.9s	remaining: 1m 28s
128:	learn: 19.1084032	total: 1m	remaining: 33.3s
16:	learn: 53.5245764	total: 4.85s	remaining: 52.2s
121:	learn: 20.3285421	total: 1m	remaining: 38.5s
129:	learn: 18.9433996	total: 1m	remaining: 32.7s
127:	learn: 19.2886068	total: 1m 3s	remaining: 35.5s
11:	learn: 55.6738657	total: 6.59s	remaining: 1m 43s
148:	learn: 3.5392109	total: 1m 3s	remaining: 21.9s
22:	learn: 50.1955523	total: 11.4s	remaining: 1m 28s
141:	learn: 3.5438331	total: 1m 4s	remaining: 26.2s
17:	learn: 53.0499139	total: 5.3s	remaining: 53.5s
149:	learn: 3.5386573	total: 1m 4s	remaining: 21.4s
130:	learn: 18.7797932	total: 1m 1s	remaining: 32.2s
122:	learn: 20.1530126	total: 1m	remaining: 38s
12:	learn: 55.1520048	total: 6.99s	remaining: 1m 40s
128:	learn: 19.1211582	total: 1m 3s	remaining: 35s
23:	learn: 49.7236541	total: 11.8s	remaining: 1m 26s
18:	learn: 52.5807824	total: 5.69s	remaining: 54.2s
131:	learn: 18.6179401	total: 1m 1s	remaining: 31.7s
13:	learn: 54.6315266	total: 7.28s	remaining: 1m 36s
142:	learn: 3.5426051	total: 1m 4s	remaining: 25.8s
150:	learn: 3.5378159	total: 1m 4s	remaining: 21s
14:	learn: 54.1157573	total: 7.45s	remaining: 1m 31s
123:	learn: 19.9793850	total: 1m 1s	remaining: 37.5s
129:	learn: 18.9558442	total: 1m 4s	remaining: 34.6s
143:	learn: 3.5417383	total: 1m 5s	remaining: 25.3s
124:	learn: 19.8063708	total: 1m 1s	remaining: 36.9s
24:	learn: 49.2579264	total: 12.4s	remaining: 1m 26s
19:	learn: 52.1176523	total: 6.26s	remaining: 56.4s
132:	learn: 18.4583093	total: 1m 2s	remaining: 31.3s
125:	learn: 19.6354261	total: 1m 1s	remaining: 36.2s
126:	learn: 19.4667961	total: 1m 1s	remaining: 35.5s
15:	learn: 53.6066564	total: 8.01s	remaining: 1m 32s
144:	learn: 3.5408817	total: 1m 5s	remaining: 24.8s
151:	learn: 3.5364432	total: 1m 5s	remaining: 20.6s
127:	learn: 19.2972471	total: 1m 1s	remaining: 34.8s
130:	learn: 18.7924152	total: 1m 4s	remaining: 34.1s
20:	learn: 51.6619110	total: 6.78s	remaining: 57.8s
16:	learn: 53.1023064	total: 8.3s	remaining: 1m 29s
25:	learn: 48.7983678	total: 13.1s	remaining: 1m 27s
128:	learn: 19.1293304	total: 1m 2s	remaining: 34.2s
133:	learn: 18.2997299	total: 1m 2s	remaining: 30.9s
21:	learn: 51.2073758	total: 7.07s	remaining: 57.2s
131:	learn: 18.6312026	total: 1m 5s	remaining: 33.6s
145:	learn: 3.5391582	total: 1m 6s	remaining: 24.4s
22:	learn: 50.7596540	total: 7.21s	remaining: 55.5s
152:	learn: 3.5351325	total: 1m 5s	remaining: 20.3s
17:	learn: 52.6046986	total: 8.8s	remaining: 1m 28s
153:	learn: 3.5339493	total: 1m 6s	remaining: 19.8s
26:	learn: 48.3433964	total: 13.6s	remaining: 1m 27s
23:	learn: 50.3155261	total: 7.43s	remaining: 54.5s
132:	learn: 18.4713869	total: 1m 5s	remaining: 33s
129:	learn: 18.9639574	total: 1m 2s	remaining: 33.8s
154:	learn: 3.5327496	total: 1m 6s	remaining: 19.3s
24:	learn: 49.8766952	total: 7.66s	remaining: 53.6s
134:	learn: 18.1432658	total: 1m 3s	remaining: 30.6s
146:	learn: 3.5378138	total: 1m 6s	remaining: 24s
27:	learn: 47.8915812	total: 14.1s	remaining: 1m 26s
18:	learn: 52.1118775	total: 9.35s	remaining: 1m 29s
25:	learn: 49.4433578	total: 7.97s	remaining: 53.4s
155:	learn: 3.5312702	total: 1m 6s	remaining: 18.8s
133:	learn: 18.3143249	total: 1m 6s	remaining: 32.6s
147:	learn: 3.5365520	total: 1m 7s	remaining: 23.6s
135:	learn: 17.9897100	total: 1m 3s	remaining: 30.1s
28:	learn: 47.4439465	total: 14.4s	remaining: 1m 24s
26:	learn: 49.0127084	total: 8.28s	remaining: 53s
130:	learn: 18.8004375	total: 1m 3s	remaining: 33.5s
19:	learn: 51.6213029	total: 9.88s	remaining: 1m 28s
148:	learn: 3.5353249	total: 1m 7s	remaining: 23.1s
134:	learn: 18.1580726	total: 1m 6s	remaining: 32.1s
156:	learn: 3.5300390	total: 1m 7s	remaining: 18.4s
27:	learn: 48.5828872	total: 8.53s	remaining: 52.4s
136:	learn: 17.8347268	total: 1m 4s	remaining: 29.6s
29:	learn: 47.0023940	total: 14.9s	remaining: 1m 24s
20:	learn: 51.1359611	total: 10.3s	remaining: 1m 27s
131:	learn: 18.6389881	total: 1m 4s	remaining: 33s
30:	learn: 46.5610814	total: 15.1s	remaining: 1m 22s
157:	learn: 3.5287204	total: 1m 7s	remaining: 18s
149:	learn: 3.5342804	total: 1m 7s	remaining: 22.6s
28:	learn: 48.1598167	total: 8.96s	remaining: 52.8s
135:	learn: 18.0045577	total: 1m 7s	remaining: 31.6s
31:	learn: 46.1283526	total: 15.4s	remaining: 1m 20s
158:	learn: 3.5278903	total: 1m 7s	remaining: 17.5s
132:	learn: 18.4793178	total: 1m 4s	remaining: 32.5s
150:	learn: 3.5333031	total: 1m 8s	remaining: 22.1s
137:	learn: 17.6830827	total: 1m 5s	remaining: 29.2s
21:	learn: 50.6580684	total: 10.9s	remaining: 1m 27s
29:	learn: 47.7400475	total: 9.39s	remaining: 53.2s
133:	learn: 18.3208291	total: 1m 4s	remaining: 31.9s
159:	learn: 3.5272255	total: 1m 8s	remaining: 17.1s
136:	learn: 17.8503750	total: 1m 7s	remaining: 31.1s
30:	learn: 47.3273946	total: 9.67s	remaining: 52.7s
32:	learn: 45.6980819	total: 16s	remaining: 1m 20s
22:	learn: 50.1828019	total: 11.3s	remaining: 1m 26s
134:	learn: 18.1651309	total: 1m 5s	remaining: 31.4s
151:	learn: 3.5318172	total: 1m 8s	remaining: 21.7s
138:	learn: 17.5329018	total: 1m 5s	remaining: 28.9s
137:	learn: 17.6982411	total: 1m 8s	remaining: 30.6s
31:	learn: 46.9205069	total: 10.1s	remaining: 52.8s
160:	learn: 3.5260154	total: 1m 8s	remaining: 16.7s
152:	learn: 3.5307125	total: 1m 9s	remaining: 21.2s
32:	learn: 46.5134477	total: 10.3s	remaining: 51.9s
139:	learn: 17.3861383	total: 1m 6s	remaining: 28.3s
135:	learn: 18.0116734	total: 1m 5s	remaining: 30.9s
33:	learn: 45.2715925	total: 16.7s	remaining: 1m 21s
23:	learn: 49.7110623	total: 12s	remaining: 1m 27s
153:	learn: 3.5291587	total: 1m 9s	remaining: 20.7s
138:	learn: 17.5482060	total: 1m 8s	remaining: 30.1s
24:	learn: 49.2453892	total: 12.2s	remaining: 1m 25s
33:	learn: 46.1132307	total: 10.7s	remaining: 52.1s
136:	learn: 17.8580992	total: 1m 6s	remaining: 30.4s
161:	learn: 3.5249531	total: 1m 9s	remaining: 16.3s
34:	learn: 45.7145218	total: 10.9s	remaining: 51.3s
140:	learn: 17.2380287	total: 1m 6s	remaining: 27.9s
34:	learn: 44.8489241	total: 17.2s	remaining: 1m 21s
25:	learn: 48.7848618	total: 12.5s	remaining: 1m 23s
139:	learn: 17.4016225	total: 1m 9s	remaining: 29.6s
35:	learn: 45.3205466	total: 11.2s	remaining: 50.8s
141:	learn: 17.0910065	total: 1m 6s	remaining: 27.3s
154:	learn: 3.5281112	total: 1m 10s	remaining: 20.4s
162:	learn: 3.5234226	total: 1m 10s	remaining: 15.9s
26:	learn: 48.3300363	total: 12.9s	remaining: 1m 22s
137:	learn: 17.7060018	total: 1m 6s	remaining: 29.9s
142:	learn: 16.9464643	total: 1m 7s	remaining: 26.8s
36:	learn: 44.9301308	total: 11.5s	remaining: 50.5s
140:	learn: 17.2535172	total: 1m 9s	remaining: 29.1s
35:	learn: 44.4332367	total: 17.9s	remaining: 1m 21s
155:	learn: 3.5272840	total: 1m 10s	remaining: 19.9s
163:	learn: 3.5225434	total: 1m 10s	remaining: 15.5s
143:	learn: 16.8037925	total: 1m 7s	remaining: 26.3s
37:	learn: 44.5465043	total: 11.8s	remaining: 50.4s
141:	learn: 17.1072748	total: 1m 9s	remaining: 28.6s
138:	learn: 17.5553368	total: 1m 7s	remaining: 29.5s
27:	learn: 47.8808600	total: 13.5s	remaining: 1m 22s
38:	learn: 44.1660571	total: 12s	remaining: 49.6s
144:	learn: 16.6620440	total: 1m 7s	remaining: 25.8s
39:	learn: 43.7851674	total: 12.2s	remaining: 48.8s
36:	learn: 44.0186205	total: 18.4s	remaining: 1m 21s
156:	learn: 3.5261420	total: 1m 11s	remaining: 19.5s
164:	learn: 3.5214035	total: 1m 11s	remaining: 15.1s
28:	learn: 47.4335992	total: 13.9s	remaining: 1m 22s
142:	learn: 16.9630214	total: 1m 10s	remaining: 28.1s
40:	learn: 43.4103910	total: 12.5s	remaining: 48.5s
145:	learn: 16.5210586	total: 1m 8s	remaining: 25.3s
139:	learn: 17.4068212	total: 1m 7s	remaining: 29.1s
157:	learn: 3.5252698	total: 1m 11s	remaining: 19s
41:	learn: 43.0417405	total: 12.8s	remaining: 48.1s
165:	learn: 3.5202133	total: 1m 11s	remaining: 14.7s
146:	learn: 16.3816398	total: 1m 8s	remaining: 24.7s
147:	learn: 16.2455096	total: 1m 8s	remaining: 24.2s
42:	learn: 42.6739302	total: 13s	remaining: 47.5s
29:	learn: 46.9920506	total: 14.6s	remaining: 1m 22s
37:	learn: 43.6065513	total: 19.3s	remaining: 1m 22s
148:	learn: 16.1098839	total: 1m 8s	remaining: 23.6s
143:	learn: 16.8212961	total: 1m 11s	remaining: 27.7s
140:	learn: 17.2586162	total: 1m 8s	remaining: 28.6s
158:	learn: 3.5242893	total: 1m 12s	remaining: 18.6s
149:	learn: 15.9755886	total: 1m 9s	remaining: 23.1s
43:	learn: 42.3132737	total: 13.4s	remaining: 47.6s
38:	learn: 43.1990593	total: 19.7s	remaining: 1m 21s
30:	learn: 46.5498152	total: 15.1s	remaining: 1m 22s
150:	learn: 15.8421794	total: 1m 9s	remaining: 22.5s
159:	learn: 3.5232231	total: 1m 12s	remaining: 18.1s
144:	learn: 16.6793782	total: 1m 11s	remaining: 27.2s
166:	learn: 3.5188879	total: 1m 12s	remaining: 14.3s
44:	learn: 41.9519853	total: 13.7s	remaining: 47.3s
141:	learn: 17.1117284	total: 1m 9s	remaining: 28.2s
31:	learn: 46.1163049	total: 15.4s	remaining: 1m 20s
151:	learn: 15.7113442	total: 1m 9s	remaining: 22s
45:	learn: 41.5975369	total: 14.1s	remaining: 47.1s
160:	learn: 3.5217167	total: 1m 12s	remaining: 17.7s
167:	learn: 3.5176562	total: 1m 12s	remaining: 13.9s
39:	learn: 42.7956196	total: 20.4s	remaining: 1m 21s
46:	learn: 41.2474137	total: 14.2s	remaining: 46.4s
145:	learn: 16.5382608	total: 1m 12s	remaining: 26.8s
152:	learn: 15.5810731	total: 1m 10s	remaining: 21.6s
168:	learn: 3.5163458	total: 1m 13s	remaining: 13.4s
32:	learn: 45.6861413	total: 15.9s	remaining: 1m 20s
47:	learn: 40.9004638	total: 14.5s	remaining: 45.9s
142:	learn: 16.9673880	total: 1m 9s	remaining: 27.8s
48:	learn: 40.5555268	total: 14.6s	remaining: 45s
146:	learn: 16.3982310	total: 1m 12s	remaining: 26.2s
161:	learn: 3.5205165	total: 1m 13s	remaining: 17.3s
40:	learn: 42.3957354	total: 21s	remaining: 1m 21s
153:	learn: 15.4522527	total: 1m 10s	remaining: 21.1s
33:	learn: 45.2597366	total: 16.5s	remaining: 1m 20s
49:	learn: 40.2135789	total: 15s	remaining: 44.9s
169:	learn: 3.5148261	total: 1m 13s	remaining: 13s
143:	learn: 16.8244599	total: 1m 10s	remaining: 27.4s
147:	learn: 16.2617489	total: 1m 13s	remaining: 25.7s
154:	learn: 15.3238440	total: 1m 10s	remaining: 20.6s
41:	learn: 42.0017888	total: 21.4s	remaining: 1m 20s
50:	learn: 39.8754021	total: 15.2s	remaining: 44.5s
162:	learn: 3.5193993	total: 1m 14s	remaining: 16.8s
51:	learn: 39.5398090	total: 15.5s	remaining: 44s
42:	learn: 41.6121790	total: 21.7s	remaining: 1m 19s
34:	learn: 44.8373343	total: 17s	remaining: 1m 20s
155:	learn: 15.1965064	total: 1m 11s	remaining: 20.1s
163:	learn: 3.5182253	total: 1m 14s	remaining: 16.4s
148:	learn: 16.1247424	total: 1m 13s	remaining: 25.2s
52:	learn: 39.2068926	total: 15.7s	remaining: 43.5s
170:	learn: 3.5133287	total: 1m 14s	remaining: 12.6s
144:	learn: 16.6829372	total: 1m 11s	remaining: 26.9s
43:	learn: 41.2270233	total: 22.1s	remaining: 1m 18s
53:	learn: 38.8774439	total: 15.9s	remaining: 43s
35:	learn: 44.4215276	total: 17.4s	remaining: 1m 19s
171:	learn: 3.5121368	total: 1m 14s	remaining: 12.2s
164:	learn: 3.5170898	total: 1m 14s	remaining: 15.9s
149:	learn: 15.9901329	total: 1m 14s	remaining: 24.7s
44:	learn: 40.8446429	total: 22.5s	remaining: 1m 17s
145:	learn: 16.5422259	total: 1m 11s	remaining: 26.4s
156:	learn: 15.0716659	total: 1m 12s	remaining: 19.8s
36:	learn: 44.0078532	total: 17.9s	remaining: 1m 18s
54:	learn: 38.5501057	total: 16.4s	remaining: 43.3s
172:	learn: 3.5107888	total: 1m 15s	remaining: 11.7s

Exception ignored in: <function ResourceTracker.__del__ at 0x7fdb1609aa20>
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

170:	learn: 13.4648676	total: 1m 24s	remaining: 14.3s
91:	learn: 28.4934874	total: 29s	remaining: 34s
193:	learn: 3.4915200	total: 1m 27s	remaining: 2.72s
72:	learn: 31.5341466	total: 35.3s	remaining: 1m 1s
177:	learn: 12.7322271	total: 1m 27s	remaining: 10.8s
65:	learn: 33.6191377	total: 30.6s	remaining: 1m 2s
184:	learn: 12.0394287	total: 1m 25s	remaining: 6.89s
92:	learn: 28.2668959	total: 29.3s	remaining: 33.7s
178:	learn: 12.6315918	total: 1m 27s	remaining: 10.3s
93:	learn: 28.0464459	total: 29.4s	remaining: 33.2s
185:	learn: 11.9470083	total: 1m 25s	remaining: 6.42s
194:	learn: 3.4907504	total: 1m 28s	remaining: 2.27s
66:	learn: 33.3105634	total: 31.1s	remaining: 1m 1s
94:	learn: 27.8281173	total: 29.6s	remaining: 32.7s
171:	learn: 13.3573820	total: 1m 24s	remaining: 13.8s
95:	learn: 27.6108670	total: 29.8s	remaining: 32.2s
179:	learn: 12.5320093	total: 1m 27s	remaining: 9.76s
195:	learn: 3.4894883	total: 1m 28s	remaining: 1.81s
186:	learn: 11.8550872	total: 1m 25s	remaining: 5.95s
73:	learn: 31.2456043	total: 36.2s	remaining: 1m 1s
96:	learn: 27.3956547	total: 30s	remaining: 31.9s
67:	learn: 33.0054292	total: 31.6s	remaining: 1m 1s
196:	learn: 3.4885125	total: 1m 29s	remaining: 1.36s
172:	learn: 13.2518040	total: 1m 25s	remaining: 13.3s
97:	learn: 27.1830265	total: 30.2s	remaining: 31.4s
180:	learn: 12.4334026	total: 1m 28s	remaining: 9.27s
74:	learn: 30.9608833	total: 36.6s	remaining: 1m
187:	learn: 11.7636448	total: 1m 26s	remaining: 5.5s
68:	learn: 32.7048376	total: 32.1s	remaining: 1m
173:	learn: 13.1471649	total: 1m 25s	remaining: 12.8s
197:	learn: 3.4877386	total: 1m 29s	remaining: 904ms
181:	learn: 12.3364833	total: 1m 28s	remaining: 8.77s
98:	learn: 26.9704475	total: 30.8s	remaining: 31.4s
75:	learn: 30.6794841	total: 37.1s	remaining: 1m
174:	learn: 13.0437327	total: 1m 26s	remaining: 12.3s
188:	learn: 11.6728214	total: 1m 26s	remaining: 5.05s
182:	learn: 12.2413687	total: 1m 29s	remaining: 8.27s
69:	learn: 32.4052141	total: 32.5s	remaining: 1m
198:	learn: 3.4868999	total: 1m 29s	remaining: 452ms
183:	learn: 12.1462629	total: 1m 29s	remaining: 7.77s
175:	learn: 12.9402705	total: 1m 26s	remaining: 11.8s
99:	learn: 26.7628110	total: 31.4s	remaining: 31.4s
76:	learn: 30.4001925	total: 37.7s	remaining: 1m
189:	learn: 11.5828775	total: 1m 27s	remaining: 4.59s
184:	learn: 12.0521418	total: 1m 29s	remaining: 7.26s
199:	learn: 3.4858596	total: 1m 30s	remaining: 0us
100:	learn: 26.5538709	total: 31.7s	remaining: 31s
70:	learn: 32.1093250	total: 33.2s	remaining: 1m
176:	learn: 12.8378476	total: 1m 27s	remaining: 11.3s
77:	learn: 30.1251583	total: 38.1s	remaining: 59.6s
185:	learn: 11.9585292	total: 1m 29s	remaining: 6.77s
101:	learn: 26.3486818	total: 31.9s	remaining: 30.7s
190:	learn: 11.4942378	total: 1m 27s	remaining: 4.13s
71:	learn: 31.8169931	total: 33.6s	remaining: 59.8s
102:	learn: 26.1444957	total: 32.2s	remaining: 30.3s
78:	learn: 29.8510927	total: 38.6s	remaining: 59.1s
103:	learn: 25.9433381	total: 32.4s	remaining: 29.9s
177:	learn: 12.7365648	total: 1m 27s	remaining: 10.8s
186:	learn: 11.8664764	total: 1m 30s	remaining: 6.3s
191:	learn: 11.4066744	total: 1m 28s	remaining: 3.68s
104:	learn: 25.7453229	total: 32.7s	remaining: 29.6s
79:	learn: 29.5813064	total: 39s	remaining: 58.4s
72:	learn: 31.5270169	total: 34.3s	remaining: 59.6s
192:	learn: 11.3208304	total: 1m 28s	remaining: 3.21s

Exception ignored in: <function ResourceTracker.__del__ at 0x7f3cf729aa20>
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

178:	learn: 12.6360377	total: 1m 28s	remaining: 10.4s
187:	learn: 11.7749255	total: 1m 31s	remaining: 5.81s
80:	learn: 29.3117177	total: 39.3s	remaining: 57.8s
105:	learn: 25.5477513	total: 33.1s	remaining: 29.3s
193:	learn: 11.2345992	total: 1m 29s	remaining: 2.75s
0:	learn: 61.8084153	total: 229ms	remaining: 45.6s
73:	learn: 31.2380079	total: 34.8s	remaining: 59.2s
106:	learn: 25.3509757	total: 33.4s	remaining: 29s
81:	learn: 29.0457149	total: 39.7s	remaining: 57.1s
179:	learn: 12.5369907	total: 1m 28s	remaining: 9.87s
188:	learn: 11.6843161	total: 1m 31s	remaining: 5.33s
107:	learn: 25.1557006	total: 33.7s	remaining: 28.7s
1:	learn: 61.2500939	total: 644ms	remaining: 1m 3s
194:	learn: 11.1499000	total: 1m 29s	remaining: 2.29s
82:	learn: 28.7812485	total: 40.1s	remaining: 56.6s
74:	learn: 30.9516891	total: 35.4s	remaining: 59s
108:	learn: 24.9628708	total: 34s	remaining: 28.4s
189:	learn: 11.5945429	total: 1m 32s	remaining: 4.85s
2:	learn: 60.6970406	total: 1.04s	remaining: 1m 8s
180:	learn: 12.4382292	total: 1m 29s	remaining: 9.38s
195:	learn: 11.0662744	total: 1m 29s	remaining: 1.83s
83:	learn: 28.5230395	total: 40.5s	remaining: 56s
109:	learn: 24.7729201	total: 34.3s	remaining: 28.1s
3:	learn: 60.1484401	total: 1.33s	remaining: 1m 5s
75:	learn: 30.6703686	total: 35.9s	remaining: 58.6s
190:	learn: 11.5056342	total: 1m 32s	remaining: 4.36s
4:	learn: 59.6055103	total: 1.51s	remaining: 58.9s
181:	learn: 12.3412800	total: 1m 29s	remaining: 8.88s
5:	learn: 59.0669456	total: 1.67s	remaining: 54s
76:	learn: 30.3913650	total: 36.2s	remaining: 57.9s
84:	learn: 28.2634420	total: 41.1s	remaining: 55.5s
110:	learn: 24.5847688	total: 34.8s	remaining: 27.9s
6:	learn: 58.5345346	total: 1.83s	remaining: 50.4s
182:	learn: 12.2468602	total: 1m 30s	remaining: 8.37s
196:	learn: 10.9826274	total: 1m 30s	remaining: 1.38s
191:	learn: 11.4187527	total: 1m 32s	remaining: 3.87s
7:	learn: 58.0100913	total: 2.1s	remaining: 50.5s
111:	learn: 24.3983929	total: 35.1s	remaining: 27.6s
77:	learn: 30.1145338	total: 36.7s	remaining: 57.3s
183:	learn: 12.1518330	total: 1m 30s	remaining: 7.87s
8:	learn: 57.4906874	total: 2.33s	remaining: 49.5s
112:	learn: 24.2150748	total: 35.4s	remaining: 27.2s
85:	learn: 28.0088509	total: 41.7s	remaining: 55.3s
192:	learn: 11.3319980	total: 1m 33s	remaining: 3.39s
197:	learn: 10.9006797	total: 1m 31s	remaining: 922ms
78:	learn: 29.8411424	total: 37.1s	remaining: 56.9s
184:	learn: 12.0575951	total: 1m 30s	remaining: 7.37s
9:	learn: 56.9781707	total: 2.64s	remaining: 50.2s
113:	learn: 24.0329346	total: 35.8s	remaining: 27s
198:	learn: 10.8198973	total: 1m 31s	remaining: 460ms
86:	learn: 27.7547619	total: 42.3s	remaining: 54.9s
193:	learn: 11.2464688	total: 1m 34s	remaining: 2.91s
185:	learn: 11.9644393	total: 1m 31s	remaining: 6.87s
10:	learn: 56.4696554	total: 3.09s	remaining: 53s
114:	learn: 23.8528715	total: 36.1s	remaining: 26.7s
79:	learn: 29.5717156	total: 37.8s	remaining: 56.7s
115:	learn: 23.6740581	total: 36.4s	remaining: 26.3s
87:	learn: 27.5049500	total: 42.7s	remaining: 54.3s
194:	learn: 11.1628874	total: 1m 34s	remaining: 2.42s
11:	learn: 55.9640693	total: 3.41s	remaining: 53.4s
199:	learn: 10.7401376	total: 1m 32s	remaining: 0us
186:	learn: 11.8724625	total: 1m 31s	remaining: 6.38s
0:	learn: 61.8551604	total: 345ms	remaining: 1m 8s
116:	learn: 23.4961422	total: 36.7s	remaining: 26.1s
80:	learn: 29.3029010	total: 38.3s	remaining: 56.3s
195:	learn: 11.0792765	total: 1m 34s	remaining: 1.94s
12:	learn: 55.4681118	total: 3.86s	remaining: 55.6s
88:	learn: 27.2586999	total: 43.3s	remaining: 54s
187:	learn: 11.7808661	total: 1m 32s	remaining: 5.89s
196:	learn: 10.9964027	total: 1m 35s	remaining: 1.45s
1:	learn: 61.2965148	total: 722ms	remaining: 1m 11s
117:	learn: 23.3202308	total: 37.2s	remaining: 25.8s

Exception ignored in: <function ResourceTracker.__del__ at 0x7f791228ea20>
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

13:	learn: 54.9758982	total: 4.17s	remaining: 55.5s
81:	learn: 29.0363527	total: 38.8s	remaining: 55.9s
197:	learn: 10.9142246	total: 1m 35s	remaining: 964ms
2:	learn: 60.7432630	total: 1.11s	remaining: 1m 12s
118:	learn: 23.1446301	total: 37.5s	remaining: 25.5s
14:	learn: 54.4882999	total: 4.51s	remaining: 55.6s
89:	learn: 27.0138254	total: 43.9s	remaining: 53.7s
188:	learn: 11.6902455	total: 1m 33s	remaining: 5.41s
198:	learn: 10.8333250	total: 1m 35s	remaining: 482ms
3:	learn: 60.1943977	total: 1.45s	remaining: 1m 10s
15:	learn: 54.0062806	total: 4.79s	remaining: 55.1s
82:	learn: 28.7722849	total: 39.4s	remaining: 55.5s
119:	learn: 22.9728505	total: 37.9s	remaining: 25.2s
16:	learn: 53.5290395	total: 4.99s	remaining: 53.7s
4:	learn: 59.6509663	total: 1.7s	remaining: 1m 6s
90:	learn: 26.7730510	total: 44.4s	remaining: 53.2s
83:	learn: 28.5144767	total: 39.7s	remaining: 54.9s
5:	learn: 59.1121030	total: 1.83s	remaining: 59.3s
199:	learn: 10.7533291	total: 1m 36s	remaining: 0us
189:	learn: 11.6002455	total: 1m 33s	remaining: 4.92s
120:	learn: 22.8013808	total: 38.3s	remaining: 25s
17:	learn: 53.0542412	total: 5.37s	remaining: 54.3s
84:	learn: 28.2543296	total: 40s	remaining: 54.1s
121:	learn: 22.6332001	total: 38.6s	remaining: 24.6s
6:	learn: 58.5792727	total: 2.21s	remaining: 1m
190:	learn: 11.5113771	total: 1m 33s	remaining: 4.43s
18:	learn: 52.5850539	total: 5.67s	remaining: 54s
91:	learn: 26.5336952	total: 45.1s	remaining: 52.9s
122:	learn: 22.4655532	total: 38.8s	remaining: 24.3s
191:	learn: 11.4235032	total: 1m 34s	remaining: 3.92s
7:	learn: 58.0544724	total: 2.6s	remaining: 1m 2s
19:	learn: 52.1217934	total: 5.97s	remaining: 53.7s
85:	learn: 27.9998004	total: 40.5s	remaining: 53.7s
92:	learn: 26.2949015	total: 45.4s	remaining: 52.3s
123:	learn: 22.3003235	total: 39.2s	remaining: 24s

Exception ignored in: <function ResourceTracker.__del__ at 0x7f5ced296a20>
Traceback (most recent call last):
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 82, in __del__
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 91, in _stop
  File "/usr/lib/python3.13/multiprocessing/resource_tracker.py", line 116, in _stop_locked
ChildProcessError: [Errno 10] No child processes

8:	learn: 57.5346622	total: 2.94s	remaining: 1m 2s
20:	learn: 51.6659891	total: 6.29s	remaining: 53.6s
124:	learn: 22.1381505	total: 39.5s	remaining: 23.7s
9:	learn: 57.0217043	total: 3.18s	remaining: 1m
86:	learn: 27.7460848	total: 41.1s	remaining: 53.4s
93:	learn: 26.0585379	total: 45.9s	remaining: 51.7s
192:	learn: 11.3366919	total: 1m 34s	remaining: 3.44s
21:	learn: 51.2113392	total: 6.64s	remaining: 53.8s
10:	learn: 56.5127997	total: 3.39s	remaining: 58.2s
125:	learn: 21.9759089	total: 39.8s	remaining: 23.4s
94:	learn: 25.8224358	total: 46.2s	remaining: 51.1s
22:	learn: 50.7634800	total: 6.96s	remaining: 53.5s
11:	learn: 56.0069396	total: 3.64s	remaining: 57.1s
193:	learn: 11.2502452	total: 1m 35s	remaining: 2.95s
126:	learn: 21.8142411	total: 40.2s	remaining: 23.1s
23:	learn: 50.3191578	total: 7.2s	remaining: 52.8s
87:	learn: 27.4961996	total: 41.8s	remaining: 53.2s
12:	learn: 55.5106110	total: 3.9s	remaining: 56.2s
95:	learn: 25.5937173	total: 46.6s	remaining: 50.5s
127:	learn: 21.6560888	total: 40.4s	remaining: 22.7s
13:	learn: 55.0180541	total: 4.1s	remaining: 54.4s
194:	learn: 11.1672939	total: 1m 35s	remaining: 2.46s
88:	learn: 27.2506131	total: 42s	remaining: 52.4s
24:	learn: 49.8828558	total: 7.54s	remaining: 52.8s
14:	learn: 54.5301073	total: 4.38s	remaining: 54.1s
25:	learn: 49.4464536	total: 7.84s	remaining: 52.5s
96:	learn: 25.3664410	total: 47.2s	remaining: 50.1s
195:	learn: 11.0836129	total: 1m 36s	remaining: 1.96s
128:	learn: 21.4981619	total: 41s	remaining: 22.5s
15:	learn: 54.0477680	total: 4.6s	remaining: 53s
89:	learn: 27.0061817	total: 42.7s	remaining: 52.1s
129:	learn: 21.3427730	total: 41.2s	remaining: 22.2s
16:	learn: 53.5702764	total: 4.84s	remaining: 52.1s
26:	learn: 49.0158624	total: 8.37s	remaining: 53.6s
97:	learn: 25.1404264	total: 47.7s	remaining: 49.7s
196:	learn: 11.0008749	total: 1m 36s	remaining: 1.47s
17:	learn: 53.0952868	total: 5.08s	remaining: 51.4s
130:	learn: 21.1877302	total: 41.5s	remaining: 21.9s
90:	learn: 26.7640691	total: 43.1s	remaining: 51.7s
27:	learn: 48.5859198	total: 8.71s	remaining: 53.5s
18:	learn: 52.6257582	total: 5.38s	remaining: 51.3s
197:	learn: 10.9190647	total: 1m 37s	remaining: 981ms
98:	learn: 24.9172493	total: 48.2s	remaining: 49.1s
0:	learn: 61.8573278	total: 511ms	remaining: 1m 41s
131:	learn: 21.0348446	total: 41.9s	remaining: 21.6s
28:	learn: 48.1676608	total: 9.02s	remaining: 53.2s
132:	learn: 20.8833013	total: 42.1s	remaining: 21.2s
91:	learn: 26.5246580	total: 43.7s	remaining: 51.3s
19:	learn: 52.1622454	total: 5.83s	remaining: 52.5s
1:	learn: 61.2985627	total: 916ms	remaining: 1m 30s
29:	learn: 47.7478585	total: 9.36s	remaining: 53s
133:	learn: 20.7341698	total: 42.4s	remaining: 20.9s
99:	learn: 24.6952671	total: 48.7s	remaining: 48.7s
198:	learn: 10.8378510	total: 1m 37s	remaining: 491ms
20:	learn: 51.7060645	total: 6.2s	remaining: 52.8s
92:	learn: 26.2857683	total: 44.1s	remaining: 50.8s
30:	learn: 47.3351921	total: 9.59s	remaining: 52.3s
2:	learn: 60.7451798	total: 1.25s	remaining: 1m 22s
93:	learn: 26.0487406	total: 44.4s	remaining: 50.1s
134:	learn: 20.5862852	total: 42.9s	remaining: 20.6s
31:	learn: 46.9244210	total: 9.88s	remaining: 51.8s
3:	learn: 60.1961972	total: 1.56s	remaining: 1m 16s
100:	learn: 24.4768893	total: 49.3s	remaining: 48.3s
199:	learn: 10.7577859	total: 1m 38s	remaining: 0us
21:	learn: 51.2488586	total: 6.71s	remaining: 54.3s
4:	learn: 59.6526464	total: 1.87s	remaining: 1m 13s
135:	learn: 20.4393171	total: 43.3s	remaining: 20.4s
32:	learn: 46.5177532	total: 10.3s	remaining: 52s
94:	learn: 25.8131230	total: 44.9s	remaining: 49.6s
22:	learn: 50.8009362	total: 7.12s	remaining: 54.8s
5:	learn: 59.1163266	total: 2.19s	remaining: 1m 10s
101:	learn: 24.2610172	total: 49.9s	remaining: 47.9s
136:	learn: 20.2953838	total: 43.6s	remaining: 20s
33:	learn: 46.1169084	total: 10.6s	remaining: 51.7s
23:	learn: 50.3579023	total: 7.36s	remaining: 53.9s
95:	learn: 25.5861189	total: 45.3s	remaining: 49.1s
137:	learn: 20.1512852	total: 43.8s	remaining: 19.7s
6:	learn: 58.5833008	total: 2.52s	remaining: 1m 9s
34:	learn: 45.7177767	total: 10.9s	remaining: 51.3s
24:	learn: 49.9187687	total: 7.65s	remaining: 53.5s
138:	learn: 20.0086947	total: 44.1s	remaining: 19.4s
35:	learn: 45.3241992	total: 11.1s	remaining: 50.5s
7:	learn: 58.0585455	total: 2.83s	remaining: 1m 8s
102:	learn: 24.0445143	total: 50.5s	remaining: 47.5s
25:	learn: 49.4823074	total: 7.91s	remaining: 52.9s
96:	learn: 25.3585394	total: 45.9s	remaining: 48.7s
139:	learn: 19.8689461	total: 44.4s	remaining: 19s
36:	learn: 44.9339216	total: 11.4s	remaining: 50.2s
26:	learn: 49.0512568	total: 8.15s	remaining: 52.2s
8:	learn: 57.5389850	total: 3.22s	remaining: 1m 8s
103:	learn: 23.8310190	total: 50.9s	remaining: 47s
37:	learn: 44.5503364	total: 11.7s	remaining: 49.8s
140:	learn: 19.7286897	total: 44.8s	remaining: 18.7s
27:	learn: 48.6213955	total: 8.5s	remaining: 52.2s
9:	learn: 57.0257788	total: 3.57s	remaining: 1m 7s
28:	learn: 48.1981200	total: 8.6s	remaining: 50.7s
97:	learn: 25.1326074	total: 46.5s	remaining: 48.4s
38:	learn: 44.1700469	total: 12s	remaining: 49.3s
141:	learn: 19.5906313	total: 45s	remaining: 18.4s
0:	learn: 61.8431091	total: 323ms	remaining: 1m 4s
104:	learn: 23.6197606	total: 51.5s	remaining: 46.6s
29:	learn: 47.7781426	total: 8.86s	remaining: 50.2s
1:	learn: 61.2844142	total: 496ms	remaining: 49.1s
39:	learn: 43.7891406	total: 12.3s	remaining: 49s
142:	learn: 19.4539033	total: 45.3s	remaining: 18.1s
10:	learn: 56.5169144	total: 4.05s	remaining: 1m 9s
30:	learn: 47.3651100	total: 9.13s	remaining: 49.8s
0:	learn: 50.6486404	total: 574ms	remaining: 56.8s
105:	learn: 23.4094116	total: 51.8s	remaining: 46s
143:	learn: 19.3179338	total: 45.6s	remaining: 17.7s
98:	learn: 24.9087682	total: 47.2s	remaining: 48.1s
2:	learn: 60.7310801	total: 912ms	remaining: 59.9s
40:	learn: 43.4150011	total: 12.7s	remaining: 49.1s
11:	learn: 56.0106539	total: 4.37s	remaining: 1m 8s
31:	learn: 46.9574418	total: 9.39s	remaining: 49.3s
99:	learn: 24.6900109	total: 47.4s	remaining: 47.4s
144:	learn: 19.1840209	total: 45.9s	remaining: 17.4s
12:	learn: 55.5105861	total: 4.59s	remaining: 1m 6s
32:	learn: 46.5518489	total: 9.61s	remaining: 48.6s
3:	learn: 60.1821979	total: 1.3s	remaining: 1m 3s
41:	learn: 43.0441064	total: 13s	remaining: 49.1s
145:	learn: 19.0511776	total: 46.1s	remaining: 17s
33:	learn: 46.1510111	total: 9.86s	remaining: 48.1s
13:	learn: 55.0164348	total: 4.86s	remaining: 1m 4s
106:	learn: 23.2025821	total: 52.5s	remaining: 45.6s
1:	learn: 41.1573904	total: 1.31s	remaining: 1m 4s
146:	learn: 18.9197327	total: 46.3s	remaining: 16.7s
42:	learn: 42.6775509	total: 13.3s	remaining: 48.7s
34:	learn: 45.7516592	total: 10s	remaining: 47.2s
4:	learn: 59.6386878	total: 1.66s	remaining: 1m 4s
100:	learn: 24.4720452	total: 48s	remaining: 47s
35:	learn: 45.3579490	total: 10.2s	remaining: 46.6s
2:	learn: 33.5307277	total: 1.65s	remaining: 53.2s
14:	learn: 54.5280097	total: 5.26s	remaining: 1m 4s
5:	learn: 59.0998094	total: 1.95s	remaining: 1m 2s
107:	learn: 22.9961877	total: 53s	remaining: 45.2s
101:	learn: 24.2564642	total: 48.3s	remaining: 46.4s
43:	learn: 42.3177565	total: 13.8s	remaining: 48.9s
147:	learn: 18.7896126	total: 46.9s	remaining: 16.5s
15:	learn: 54.0456628	total: 5.52s	remaining: 1m 3s
3:	learn: 27.4114866	total: 1.93s	remaining: 46.3s
44:	learn: 41.9560647	total: 13.9s	remaining: 48s
36:	learn: 44.9674047	total: 10.7s	remaining: 46.9s
6:	learn: 58.5669522	total: 2.33s	remaining: 1m 4s
45:	learn: 41.6011164	total: 14.2s	remaining: 47.4s
16:	learn: 53.5680056	total: 5.84s	remaining: 1m 2s
148:	learn: 18.6610668	total: 47.3s	remaining: 16.2s
4:	learn: 22.5113004	total: 2.3s	remaining: 43.8s
108:	learn: 22.7930889	total: 53.6s	remaining: 44.7s
37:	learn: 44.5836643	total: 11s	remaining: 46.8s
102:	learn: 24.0395420	total: 48.9s	remaining: 46.1s
7:	learn: 58.0420147	total: 2.7s	remaining: 1m 4s
149:	learn: 18.5332090	total: 47.4s	remaining: 15.8s
46:	learn: 41.2509828	total: 14.5s	remaining: 47.3s
38:	learn: 44.2030473	total: 11.2s	remaining: 46.3s
8:	learn: 57.5222244	total: 2.88s	remaining: 1m 1s
5:	learn: 18.5766275	total: 2.64s	remaining: 41.4s
150:	learn: 18.4073053	total: 47.7s	remaining: 15.5s
47:	learn: 40.9012697	total: 14.8s	remaining: 46.7s
109:	learn: 22.5922691	total: 54.1s	remaining: 44.3s
39:	learn: 43.8221520	total: 11.5s	remaining: 46s
17:	learn: 53.0929078	total: 6.51s	remaining: 1m 5s
103:	learn: 23.8262926	total: 49.4s	remaining: 45.6s
9:	learn: 57.0091850	total: 3.22s	remaining: 1m 1s
6:	learn: 15.4406967	total: 3.08s	remaining: 40.9s
40:	learn: 43.4468533	total: 11.7s	remaining: 45.3s
151:	learn: 18.2823166	total: 48.1s	remaining: 15.2s
18:	learn: 52.6236187	total: 6.81s	remaining: 1m 4s
48:	learn: 40.5566888	total: 15.2s	remaining: 46.7s
110:	learn: 22.3950915	total: 54.5s	remaining: 43.7s
41:	learn: 43.0780947	total: 11.9s	remaining: 44.9s
104:	learn: 23.6140870	total: 49.9s	remaining: 45.1s
152:	learn: 18.1583913	total: 48.4s	remaining: 14.9s
10:	learn: 56.5002559	total: 3.67s	remaining: 1m 3s
19:	learn: 52.1599314	total: 7.04s	remaining: 1m 3s
49:	learn: 40.2152720	total: 15.4s	remaining: 46.2s
7:	learn: 12.9266366	total: 3.52s	remaining: 40.5s
111:	learn: 22.1984075	total: 54.9s	remaining: 43.1s
42:	learn: 42.7097305	total: 12.3s	remaining: 44.8s
11:	learn: 55.9976169	total: 3.95s	remaining: 1m 1s
153:	learn: 18.0366067	total: 48.7s	remaining: 14.6s
20:	learn: 51.7034167	total: 7.38s	remaining: 1m 2s
43:	learn: 42.3488161	total: 12.4s	remaining: 44s
12:	learn: 55.4976903	total: 4.13s	remaining: 59.4s
50:	learn: 39.8776102	total: 15.8s	remaining: 46.3s
8:	learn: 10.9264347	total: 3.96s	remaining: 40.1s
51:	learn: 39.5423649	total: 16s	remaining: 45.5s
105:	learn: 23.4031926	total: 50.6s	remaining: 44.9s
13:	learn: 55.0035636	total: 4.37s	remaining: 58s
21:	learn: 51.2460640	total: 7.75s	remaining: 1m 2s
44:	learn: 41.9876429	total: 12.8s	remaining: 44.1s
112:	learn: 22.0024903	total: 55.5s	remaining: 42.8s
14:	learn: 54.5152703	total: 4.53s	remaining: 55.8s
154:	learn: 17.9152924	total: 49.3s	remaining: 14.3s
52:	learn: 39.2097199	total: 16.3s	remaining: 45.1s
45:	learn: 41.6312541	total: 13.1s	remaining: 43.8s
22:	learn: 50.7975339	total: 8.09s	remaining: 1m 2s
15:	learn: 54.0329359	total: 4.77s	remaining: 54.8s
53:	learn: 38.8806260	total: 16.5s	remaining: 44.7s
106:	learn: 23.1965783	total: 51.1s	remaining: 44.4s
113:	learn: 21.8101401	total: 55.9s	remaining: 42.2s
16:	learn: 53.5533427	total: 4.99s	remaining: 53.7s
46:	learn: 41.2810789	total: 13.3s	remaining: 43.4s
23:	learn: 50.3542989	total: 8.34s	remaining: 1m 1s
9:	learn: 9.3651214	total: 4.74s	remaining: 42.7s
155:	learn: 17.7964814	total: 49.7s	remaining: 14s
156:	learn: 17.6779935	total: 49.9s	remaining: 13.7s
17:	learn: 53.0783892	total: 5.22s	remaining: 52.8s
47:	learn: 40.9340945	total: 13.6s	remaining: 43.1s
24:	learn: 49.9151438	total: 8.65s	remaining: 1m
107:	learn: 22.9902891	total: 51.6s	remaining: 44s
157:	learn: 17.5602875	total: 50.1s	remaining: 13.3s
18:	learn: 52.6099461	total: 5.39s	remaining: 51.3s
10:	learn: 8.1310245	total: 5.15s	remaining: 41.7s
48:	learn: 40.5887748	total: 13.8s	remaining: 42.5s
114:	learn: 21.6182032	total: 56.6s	remaining: 41.8s
54:	learn: 38.5534174	total: 17.3s	remaining: 45.5s
11:	learn: 7.1792339	total: 5.35s	remaining: 39.2s
49:	learn: 40.2464299	total: 14s	remaining: 42s
158:	learn: 17.4438115	total: 50.4s	remaining: 13s
19:	learn: 52.1463936	total: 5.72s	remaining: 51.5s
55:	learn: 38.2324874	total: 17.4s	remaining: 44.8s
25:	learn: 49.4763062	total: 9.08s	remaining: 1m
56:	learn: 37.9191907	total: 17.6s	remaining: 44.1s
12:	learn: 6.4435612	total: 5.7s	remaining: 38.1s
20:	learn: 51.6900834	total: 5.97s	remaining: 50.9s
159:	learn: 17.3284668	total: 50.7s	remaining: 12.7s
57:	learn: 37.5994644	total: 17.7s	remaining: 43.4s
26:	learn: 49.0454150	total: 9.39s	remaining: 1m
108:	learn: 22.7869844	total: 52.3s	remaining: 43.7s
115:	learn: 21.4293323	total: 57.1s	remaining: 41.4s
50:	learn: 39.9081906	total: 14.5s	remaining: 42.4s
160:	learn: 17.2138892	total: 51s	remaining: 12.3s
58:	learn: 37.2837467	total: 17.9s	remaining: 42.9s
21:	learn: 51.2326752	total: 6.24s	remaining: 50.5s
51:	learn: 39.5726126	total: 14.8s	remaining: 42s
59:	learn: 36.9758706	total: 18.2s	remaining: 42.4s
13:	learn: 5.8861850	total: 6.22s	remaining: 38.2s
109:	learn: 22.5846472	total: 52.7s	remaining: 43.1s
27:	learn: 48.6156306	total: 9.85s	remaining: 1m
22:	learn: 50.7845869	total: 6.55s	remaining: 50.4s
52:	learn: 39.2398505	total: 15s	remaining: 41.6s
116:	learn: 21.2419327	total: 57.8s	remaining: 41s
60:	learn: 36.6686881	total: 18.5s	remaining: 42.1s
161:	learn: 17.0979309	total: 51.5s	remaining: 12.1s
14:	learn: 5.4573788	total: 6.65s	remaining: 37.7s
28:	learn: 48.1967318	total: 10.3s	remaining: 1m
110:	learn: 22.3877049	total: 53.2s	remaining: 42.7s
23:	learn: 50.3401073	total: 6.95s	remaining: 51s
162:	learn: 16.9832310	total: 51.8s	remaining: 11.7s
53:	learn: 38.9099473	total: 15.4s	remaining: 41.5s
117:	learn: 21.0552705	total: 58.2s	remaining: 40.4s
24:	learn: 49.9009698	total: 7.25s	remaining: 50.7s
61:	learn: 36.3615673	total: 19s	remaining: 42.2s
163:	learn: 16.8721722	total: 52s	remaining: 11.4s
54:	learn: 38.5827743	total: 15.6s	remaining: 41.2s
15:	learn: 5.1270690	total: 7.08s	remaining: 37.2s
25:	learn: 49.4644594	total: 7.49s	remaining: 50.1s
29:	learn: 47.7766252	total: 10.8s	remaining: 1m 1s
164:	learn: 16.7604013	total: 52.3s	remaining: 11.1s
111:	learn: 22.1911382	total: 53.8s	remaining: 42.3s
16:	learn: 4.8735004	total: 7.34s	remaining: 35.8s
55:	learn: 38.2608024	total: 15.9s	remaining: 41s
62:	learn: 36.0599556	total: 19.4s	remaining: 42.2s
26:	learn: 49.0338688	total: 7.75s	remaining: 49.7s
30:	learn: 47.3634447	total: 11.1s	remaining: 1m
165:	learn: 16.6516795	total: 52.5s	remaining: 10.8s
118:	learn: 20.8718487	total: 58.9s	remaining: 40.1s
112:	learn: 21.9945034	total: 54.1s	remaining: 41.7s
56:	learn: 37.9430397	total: 16.3s	remaining: 40.9s
63:	learn: 35.7600945	total: 19.8s	remaining: 42s
27:	learn: 48.6040976	total: 8.08s	remaining: 49.6s
17:	learn: 4.6884929	total: 7.83s	remaining: 35.7s
119:	learn: 20.6903106	total: 59.1s	remaining: 39.4s
31:	learn: 46.9525622	total: 11.5s	remaining: 1m
166:	learn: 16.5442439	total: 52.9s	remaining: 10.5s
57:	learn: 37.6238249	total: 16.5s	remaining: 40.4s
58:	learn: 37.3071613	total: 16.6s	remaining: 39.8s
28:	learn: 48.1836297	total: 8.42s	remaining: 49.7s
18:	learn: 4.5396052	total: 8.28s	remaining: 35.3s
59:	learn: 36.9991137	total: 16.9s	remaining: 39.4s
120:	learn: 20.5120055	total: 59.6s	remaining: 38.9s
113:	learn: 21.8003531	total: 54.8s	remaining: 41.4s
64:	learn: 35.4628020	total: 20.3s	remaining: 42.1s
32:	learn: 46.5468894	total: 11.9s	remaining: 1m
29:	learn: 47.7637980	total: 8.6s	remaining: 48.7s
167:	learn: 16.4375909	total: 53.4s	remaining: 10.2s
33:	learn: 46.1460081	total: 12.1s	remaining: 58.9s
60:	learn: 36.6927289	total: 17.2s	remaining: 39.3s
65:	learn: 35.1679431	total: 20.6s	remaining: 41.8s
114:	learn: 21.6081577	total: 55.2s	remaining: 40.8s
30:	learn: 47.3511236	total: 8.98s	remaining: 48.9s
121:	learn: 20.3324413	total: 1m	remaining: 38.4s
34:	learn: 45.7460462	total: 12.3s	remaining: 58.2s
66:	learn: 34.8769627	total: 20.7s	remaining: 41.1s
168:	learn: 16.3325188	total: 53.8s	remaining: 9.86s
61:	learn: 36.3860574	total: 17.5s	remaining: 38.9s
19:	learn: 4.4298953	total: 8.91s	remaining: 35.6s
35:	learn: 45.3519540	total: 12.5s	remaining: 57s
169:	learn: 16.2276470	total: 54s	remaining: 9.53s
36:	learn: 44.9635195	total: 12.7s	remaining: 55.8s
115:	learn: 21.4194566	total: 55.6s	remaining: 40.3s
62:	learn: 36.0850466	total: 17.8s	remaining: 38.7s
20:	learn: 4.3472571	total: 9.23s	remaining: 34.7s
31:	learn: 46.9404334	total: 9.49s	remaining: 49.8s
37:	learn: 44.5797085	total: 12.9s	remaining: 54.9s
67:	learn: 34.5891791	total: 21.3s	remaining: 41.3s
122:	learn: 20.1566965	total: 1m	remaining: 38s
170:	learn: 16.1238647	total: 54.4s	remaining: 9.23s
116:	learn: 21.2325342	total: 56s	remaining: 39.7s
32:	learn: 46.5352225	total: 9.82s	remaining: 49.7s
38:	learn: 44.1988261	total: 13.2s	remaining: 54.5s
68:	learn: 34.3043837	total: 21.6s	remaining: 41s
63:	learn: 35.7854875	total: 18.3s	remaining: 38.8s
21:	learn: 4.2801254	total: 9.71s	remaining: 34.4s
117:	learn: 21.0457062	total: 56.3s	remaining: 39.1s
171:	learn: 16.0203898	total: 54.8s	remaining: 8.92s
69:	learn: 34.0217812	total: 21.8s	remaining: 40.5s
33:	learn: 46.1341433	total: 10.2s	remaining: 49.6s
39:	learn: 43.8179262	total: 13.5s	remaining: 54.2s
123:	learn: 19.9818464	total: 1m 1s	remaining: 37.5s
64:	learn: 35.4914111	total: 18.6s	remaining: 38.7s
172:	learn: 15.9163601	total: 55s	remaining: 8.59s
118:	learn: 20.8619101	total: 56.6s	remaining: 38.5s
22:	learn: 4.2207681	total: 10.1s	remaining: 33.9s
70:	learn: 33.7426340	total: 22.2s	remaining: 40.3s
65:	learn: 35.1965834	total: 18.8s	remaining: 38.2s
34:	learn: 45.7345851	total: 10.6s	remaining: 49.8s
40:	learn: 43.4424986	total: 13.9s	remaining: 54.1s
66:	learn: 34.9049233	total: 19s	remaining: 37.7s
173:	learn: 15.8165902	total: 55.5s	remaining: 8.29s
23:	learn: 4.1774083	total: 10.5s	remaining: 33.2s
41:	learn: 43.0734990	total: 14.1s	remaining: 53.2s
71:	learn: 33.4649567	total: 22.5s	remaining: 40s
124:	learn: 19.8088006	total: 1m 1s	remaining: 37.1s
174:	learn: 15.7177264	total: 55.7s	remaining: 7.95s
119:	learn: 20.6809395	total: 57.2s	remaining: 38.1s
42:	learn: 42.7042240	total: 14.3s	remaining: 52.3s
67:	learn: 34.6161046	total: 19.4s	remaining: 37.6s
24:	learn: 4.1289913	total: 10.8s	remaining: 32.3s
175:	learn: 15.6184672	total: 55.9s	remaining: 7.62s
35:	learn: 45.3406539	total: 11.1s	remaining: 50.6s
72:	learn: 33.1921209	total: 22.9s	remaining: 39.8s
43:	learn: 42.3432790	total: 14.6s	remaining: 51.7s
120:	learn: 20.5025701	total: 57.5s	remaining: 37.6s
73:	learn: 32.9238138	total: 23s	remaining: 39.2s
68:	learn: 34.3313694	total: 19.7s	remaining: 37.5s
44:	learn: 41.9818753	total: 14.8s	remaining: 50.9s
176:	learn: 15.5210935	total: 56.2s	remaining: 7.3s
25:	learn: 4.0885977	total: 11.3s	remaining: 32.1s
69:	learn: 34.0495329	total: 19.9s	remaining: 37s
36:	learn: 44.9501339	total: 11.6s	remaining: 51.1s
125:	learn: 19.6378087	total: 1m 2s	remaining: 36.8s
74:	learn: 32.6547502	total: 23.3s	remaining: 38.9s
121:	learn: 20.3237183	total: 58s	remaining: 37.1s
45:	learn: 41.6259273	total: 15.1s	remaining: 50.5s
177:	learn: 15.4247122	total: 56.5s	remaining: 6.99s
70:	learn: 33.7715319	total: 20.2s	remaining: 36.6s
75:	learn: 32.3882152	total: 23.6s	remaining: 38.5s
26:	learn: 4.0645998	total: 11.7s	remaining: 31.6s
71:	learn: 33.4939270	total: 20.4s	remaining: 36.2s
122:	learn: 20.1482190	total: 58.3s	remaining: 36.5s
126:	learn: 19.4679384	total: 1m 3s	remaining: 36.2s
46:	learn: 41.2754779	total: 15.4s	remaining: 50.3s
37:	learn: 44.5665333	total: 12.1s	remaining: 51.7s
178:	learn: 15.3268232	total: 56.9s	remaining: 6.68s
123:	learn: 19.9740424	total: 58.5s	remaining: 35.8s
76:	learn: 32.1259386	total: 23.9s	remaining: 38.2s
77:	learn: 31.8654231	total: 24.1s	remaining: 37.7s
179:	learn: 15.2318961	total: 57.1s	remaining: 6.35s
27:	learn: 4.0360876	total: 12.2s	remaining: 31.3s
72:	learn: 33.2192895	total: 20.8s	remaining: 36.2s
47:	learn: 40.9252999	total: 15.8s	remaining: 50.2s
38:	learn: 44.1859512	total: 12.5s	remaining: 51.6s
127:	learn: 19.2988555	total: 1m 3s	remaining: 35.7s
78:	learn: 31.6070290	total: 24.2s	remaining: 37.1s
73:	learn: 32.9504366	total: 21s	remaining: 35.7s
28:	learn: 4.0132341	total: 12.4s	remaining: 30.4s
124:	learn: 19.8011647	total: 59s	remaining: 35.4s
79:	learn: 31.3509269	total: 24.4s	remaining: 36.7s
48:	learn: 40.5802004	total: 16.1s	remaining: 49.7s
39:	learn: 43.8051891	total: 12.9s	remaining: 51.6s
180:	learn: 15.1387342	total: 57.6s	remaining: 6.05s
128:	learn: 19.1312748	total: 1m 3s	remaining: 35.2s
74:	learn: 32.6807774	total: 21.3s	remaining: 35.6s

In [38]:
if cat_rmsle < xgb_rmsle:
    best_model = cat_search.best_estimator_
    best_name = "CatBoost"
else:
    best_model = xgb_search.best_estimator_
    best_name = "XGBoost"

print("Best Model Selected:", best_name)

Best Model Selected: XGBoost

In [39]:
test.head()

       id     Sex  Age  Height  Weight  Duration  Heart_Rate  Body_Temp
0  750000    male   45   177.0    81.0       7.0        87.0       39.8
1  750001    male   26   200.0    97.0      20.0       101.0       40.5
2  750002  female   29   188.0    85.0      16.0       102.0       40.4
3  750003  female   39   172.0    73.0      20.0       107.0       40.6
4  750004  female   30   173.0    67.0      16.0        94.0       40.5

In [43]:
train.columns

Index(['id', 'sex', 'age', 'height', 'weight', 'duration', 'heart_rate',
       'body_temp', 'calories', 'bmi'],
      dtype='object')

In [46]:
test = test.rename(columns={
    "Sex": "sex",
    "Age": "age",
    "Height": "height",
    "Weight": "weight",
    "Duration": "duration",
    "Heart_Rate": "heart_rate",
    "Body_Temp": "body_temp",
}) 
test["bmi"] = test["weight"]/(test["height"]/(100)**2)
test["sex"] = test["sex"].map({'male': 1, 'female': 0})


X_test = test.drop(columns=["id"])

In [47]:
predictions = best_model.predict(X_test)

In [48]:
predictions

array([ 27.685099, 108.42111 ,  86.41041 , ...,  73.17721 , 168.84088 ,
        77.332245], shape=(250000,), dtype=float32)

In [49]:
# submission file 

submission = pd.DataFrame({
    "id": test["id"],
    "Calories": predictions
})

In [50]:
submission

            id    Calories
0       750000   27.685099
1       750001  108.421112
2       750002   86.410408
3       750003  126.440765
4       750004   76.623466
...        ...         ...
249995  999995   26.063120
249996  999996    9.209196
249997  999997   73.177208
249998  999998  168.840881
249999  999999   77.332245

[250000 rows x 2 columns]

In [51]:
submission.to_csv('submission.csv', index=False)

In [52]:
print(xgb_rmsle)

0.06179780223199775